Filter workflow
assurance-maladie-digital/design-system pull request #1102
Opened 2021-05-18 08:45 UTC by PYKEngine

## Description

Mise en place d'un composant servant à filtrer les entrées dans les tableaux de données

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Refactoring
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [X] Ma Pull Request pointe vers la bonne branche
- [X] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2021-05-26 13:20 UTC, deraw commented
Je pense qu'on pourrait réorganiser les composants, seul le composant `FilterModule` est réellement prévu pour être utilisé directement, les deux autres composants sont ses enfants
Il faudrait les déplacer dans le dossier `FilterModule` (comme pour la `DataList`) et ne pas les enregistrer au niveau global

2021-05-26 13:53 UTC, deraw requested changes
Première review rapide

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +	import { mdiPencil } from '@mdi/js';
```suggestion
	import { mdiCloseCircle, mdiWindowClose, mdiPencil } from '@mdi/js';
```
On peut grouper ces trois imports je pense !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +		editFilters(index: number): void {
Il me semble que l'on n'édite qu'un seul filtre ici comme on passe un index en paramètre, il faudrait renommer la méthode en `editFilter` (et l'évènement également) !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +		clearFiltersRow(index: number): void {
Idem ici on ne traite qu'un filtre donc on peut mettre au singulier, je pense que l'on peut même retirer `row` pour être cohérent avec les autres méthodes, on peut donc renommer en `clearFilter`

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/types.d.ts
> +	filter: Field
```suggestion
	index: number;
	filter: Field;
```

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterSelector/FilterSelector.vue
> +<style lang="scss" scoped>
On peut supprimer ce bloc

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +							@click="editFilters(item.index)"
Attention attacher un évènement `click` à une `div` n'est pas du tout accessible. Une `div` ne peut pas recevoir le focus lors de la navigation au clavier, n'est pas annoncée comme un élément interactif par les lecteurs d'écrans et ne dispose pas des raccourcis clavier nécessaires.
Il faudrait remplacer la `div` par un `VBtn`

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +							<!--<div class="my-2">
Attention au code mort !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +				style="text-transform:lowercase;"
Attention on ne met pas de styles inline car ils ont une spécificité trop importante, il devrait être possible d'utiliser des classes Vuetify ici, et sinon on peut ajouter des styles dans la partie `<style>`

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +					<div style="display: flex; align-items:center;">
Idem pour les styles inline ici

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +							<VIcon color="black">
Est-ce la bonne couleur pour les icônes ? 🤔

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +					filter: filter
```suggestion
					index,
					filter
```
Ici tu peux simplifier et éviter la répétition

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +				filter.value ? displayedFilters.push(item) : '';
Cette ternaire avec la chaîne vide me semble étrange, est-ce que ça ne serait pas mieux de faire un `if` ?

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +			return `${this.displayFiltersRow.length} ${this.displayFiltersRow.length > 1 ? 'filtres' : 'filtre'}`;
Le texte `filtre` avec la mise au pluriel devrait être dans un fichier `locales.ts` je pense !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterSelector/FilterSelector.vue
> +			<v-btn
`VBtn` plutôt !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterSelector/FilterSelector.vue
> +				Filtres
Ce texte devrait être dans un fichier `locales`

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/elements/FilterSelector/FilterSelector.vue
> +				<VListItemTitle @click="openModal(index)">
Je ne vois pas d'évènement `click` prévu sur ce composant https://vuetifyjs.com/en/api/v-list-item-title/, ça revient à mettre cet évènement sur une `div` !

2021-05-26 13:53 UTC, deraw commented on packages/vue-dot/src/patterns/FilterModule/FilterModule.vue
> +	);
```suggestion
	const MixinsDeclaration = mixins(Props, customizable(config));
```

2021-05-26 15:25 UTC, PYKEngine commented on packages/vue-dot/src/elements/FilterManager/FilterManager.vue
> +							<VIcon color="black">
v-bind="options.icon" ?

2021-05-28 16:21 UTC, deraw approved these changes

2021-05-28 16:24 UTC, merged