Feat/external links
assurance-maladie-digital/design-system pull request #1105
Opened 2021-05-20 00:14 UTC by mmi16389

## Description

Création du composant ExternalLinks
- la gestion des lien externes
- 
## Playground
<template>
	<div>
		
		<external-links :items="links" />
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';
	import { ExternalLink } from '../src/elements/ExternalLinks/types';

	@Component
	export default class Playground extends Vue {
		links:ExternalLink[]  = [
			{
				href: 'www.facebook.com',
				text: 'Vers facebook'
			},
			{
				href: 'www.google.com',
				text: 'Vers google'
			},
			{
				href: 'www.yahoo.com',
				text: 'Vers Yahoo'
			} 
		];
	}
</script>

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2021-05-20 14:41 UTC, deraw requested changes

2021-05-20 14:41 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +				required: false,
```suggestion
```

2021-05-20 14:41 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
```suggestion
		mounted(): void {
			this.positionTop = this.getDistanceFromTop();
		}
```

2021-05-20 19:01 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
> +			'vuex': '^3.4.0'
tu peux mettre à jour ta branche j'ai mergé cette modif dans la PR #1110

2021-05-27 10:42 UTC, mmi16389 reviewed
oki for checks

2021-06-01 09:09 UTC, mmi16389 reviewed
oko

2021-06-03 11:54 UTC, deraw approved these changes

2021-06-08 07:47 UTC, Kelhel approved these changes

2021-06-08 08:32 UTC, PYKEngine approved these changes

2021-06-08 08:58 UTC, merged