Docs/external links
assurance-maladie-digital/design-system pull request #1190
Opened 2021-06-25 08:29 UTC by mmi16389

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Documentation 

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2021-06-25 10:11 UTC, PYKEngine requested changes

2021-06-28 08:21 UTC, mmi16389 reviewed
Oki  por la review

2021-06-28 11:49 UTC, mmi16389 commented on packages/docs/src/content/examples/external-links/bottom-left.vue
> +  </v-card>
C'est oki

2021-06-28 11:49 UTC, mmi16389 commented on packages/docs/src/content/examples/external-links/bottom-right.vue
> +  </v-card>
Oki

2021-06-28 11:49 UTC, mmi16389 commented on packages/docs/src/content/examples/external-links/options.vue
> +    </v-card>
oki

2021-06-28 11:50 UTC, mmi16389 commented on packages/docs/src/content/examples/external-links/top-left.vue
> +  </v-card>
oki

2021-06-28 11:50 UTC, mmi16389 commented on packages/docs/src/content/examples/external-links/usage.vue
> +  </v-card>
oki

2021-06-28 11:50 UTC, mmi16389 commented on packages/docs/src/data/api/external-links.ts
> +}
oki

2021-06-29 20:34 UTC, mmi16389 reviewed
oki

2021-06-30 09:52 UTC, PYKEngine approved these changes

2021-07-01 14:43 UTC, deraw approved these changes

2021-07-01 14:53 UTC, merged