Bug fix/1223
assurance-maladie-digital/design-system pull request #1263
Opened 2021-07-19 07:56 UTC by mmi16389

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2021-07-19 10:45 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +			return contentClass;
Pourquoi avoir modifié cette partie ?

2021-07-19 10:45 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +			isDefault: {
Pourquoi avoir mis une nouvelle prop ? 🤔 ça devrait être automatique et transparent pour l'utilisateur non ?

2021-07-19 10:45 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}>;
à quoi correspond cette partie ?

2021-07-19 11:15 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +			return contentClass;
J'avais choisi la solution la plus simple, Mais si ça devait être transparent pour l'utilisateur c'est pas top!!!

2021-07-19 11:19 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +			isDefault: {
Dans mon implémentation, c'était de choisir une variable témoin servant à  redéfinir getter menuClass.  Quand on a left ou right de 12px. Mais comme susmentionné c'est pas top si c'est caché pour l'utilisateur.

2021-07-19 11:21 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}>;
C'est un oublie de ma part,  c'était ma première approche. Afin de détecter la position du menu.  Je vais revoir ça... s'il faut cacher ça à utilisateur

2021-07-21 14:38 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +				});
En effet!

2021-07-22 14:40 UTC, deraw requested changes
Est-ce que tu peux mettre à jour le changelog aussi stp ?

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
```suggestion
		setMenuClass(): void {
			const vuetifyThreshold = 12;
			const position = this.computedPosition.x;
			const nudge = parseInt(this.$refs.menu.calculatedLeft);

			let positionClass = '';

			if (nudge < vuetifyThreshold) {
				positionClass = ` ${position}-0`;
			}

			this.menuClass = 'vd-external-links-menu' + positionClass;
		}
```
Quelques modifications :
- correction de l'indentation
- utilisation d'un nombre pour comparer la valeur
- utilisation de `this.computedPosition.x` pour récupérer la position
- utilisation d'une variable pour ne pas dupliquer la classe `vd-external-links-menu`

⚠️ Il reste quand même un bug important à corriger
Lorsque le composant est positionné à droite (`top right` par exemple), le menu n'est pas collé à droite parce que l'on utilise uniquement `calculatedLeft` !

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
```suggestion
		setMenuPosition(): void {
			setTimeout(() => this.setMenuClass());
		}
```
J'ai vérifié de mon côté, en effet c'est pas trop possible de se passer d'un `setTimeout`, par contre pas besoin de spécifier un délai
Aussi on peut se passer de l'utilisation du hook `updated` en appelant la méthode lors du clic sur le bouton

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
>  		}
À supprimer, le getter ne sert plus autant utiliser directement la variable

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		menuClassLeftOrRight = '';
```suggestion
		menuClass = '';
```

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		isClicked = false;
```suggestion
```
Plus besoin de cette variable

2021-07-22 14:40 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +				@click="isClicked=true"
```suggestion
				@click="setMenuPosition"
```
Ici on peut appeler la méthode directement plutôt que de passer par une variable

2021-07-22 19:42 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
Good, thx!

2021-07-22 20:11 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
En effet, je viens de me rendre compte

2021-07-22 22:30 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		isClicked = false;
ça marche

2021-07-22 22:31 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		}
C'est fait, j'ai remodifié, l'implementation de la methode `setMenuClass` afin de prendre en compte cette regle

2021-07-27 14:29 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +				styles: StylesField
```suggestion
				styles: StylesField;
```

2021-07-27 15:46 UTC, deraw approved these changes

2021-07-27 15:50 UTC, merged