ticket: 1221
assurance-maladie-digital/design-system pull request #1268
Opened 2021-07-20 06:29 UTC by mmi16389

## Description

## Playground
 
<details>

```vue

<template>
	<div>
		
		<FranceConnectBtn />
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {

	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2021-07-20 06:57 UTC, PYKEngine commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +			@mouseleave="iconColor='#034ea2'"
Pourquoi ne pas l'avoir géré avec du css?

2021-07-20 07:00 UTC, PYKEngine commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +		/></svg>
Des petits soucis d'indentation sur cette partie de ton code

2021-07-20 07:03 UTC, PYKEngine commented on packages/vue-dot/src/elements/FranceConnectBtn/locales.ts
> +	btnText: 'S’identifier avec France Connect'
Ne serait-ce pas plus parlant avec btnLabel?

2021-07-20 07:04 UTC, PYKEngine commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +			iconName: {
Je renommerais bien cette props en "label"

2021-07-20 07:06 UTC, PYKEngine commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +		}
A vérifier, mais je crois qu'il existe une classe MD pour cursor: pointer

2021-07-21 12:05 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +		/></svg>
c'est oki

2021-07-21 12:40 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +			@mouseleave="iconColor='#034ea2'"
j'avais essayé ça n'a pas marché pour moi. Je peux creuser plus pour voir...

2021-07-21 12:52 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/locales.ts
> +	btnText: 'S’identifier avec France Connect'
J'ai remarqué dans la convention de nommage de vuetify on utilise plus: Text ou title.  Label! certes c'est plus parlant. Il faut qu'on en discute si on doit adapter tous nos composants qui probablement utilisent ces meme criteres...

2021-07-21 12:55 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +			iconName: {
pareil comme le dernier commentaire.  Disons: iconText ou iconTitle qu'est ce que tu en penses

2021-07-21 14:58 UTC, PYKEngine approved these changes

2021-07-22 09:39 UTC, mmi16389 reviewed
Check ok!

2021-07-22 12:58 UTC, deraw requested changes

2021-07-22 12:58 UTC, deraw commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		ref="menu"
Il ne devrait pas y avoir de modifications dans ce fichier

2021-07-22 12:58 UTC, deraw commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +				<title>{{ iconText }}</title>
Est-ce que tu peux sauter une ligne entre les balises stp ?

2021-07-22 12:58 UTC, deraw commented on packages/vue-dot/src/elements/FranceConnectBtn/locales.ts
> +	href: 'https://app.franceconnect.gouv.fr/'
Pourquoi avoir mis l'URL dans les `locales` ?

2021-07-22 22:40 UTC, mmi16389 commented on packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
> +		ref="menu"
Oui en effet!.. ptit loupé de merge :)

2021-07-22 22:43 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/locales.ts
> +	href: 'https://app.franceconnect.gouv.fr/'
je me suis posé la question???

2021-07-22 22:46 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +				<title>{{ iconText }}</title>
c'est fait

2021-07-22 23:04 UTC, mmi16389 commented on packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
> +			@click="urlConnect"
Oki je vois... J'ai pas pu malheureusement m'inspirer de l'exitant! Prob de VPN :).  Sinon je viens de faire une mise  jour du code, j'ai ajouté une balise a pour le lien externe

2021-07-27 14:02 UTC, deraw approved these changes

2021-07-27 14:40 UTC, merged