Add design system colors to vuetify theme
assurance-maladie-digital/design-system pull request #2191
Opened 2022-08-01 09:08 UTC by Julien-Baylac

## Description

Ajout des classes design system aux classes vuetify

## Type de changement

- Nouvelle fonctionnalité

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2022-08-01 14:59 UTC, Kelhel commented
Tu l'as juste ajouté au playground de vue-dot, il faut aussi faire la même chose sur le template du starterkit

2022-08-01 15:01 UTC, Kelhel commented
Faut il aussi faire cet ajout à la lib vue-dot en elle même ? Si oui toutes les couleurs vuetify qui sont utilisées doivent être remplacé ? ou on fusionne nos couleur et celles de vuetify ?

2022-08-08 10:12 UTC, deraw requested changes
Il faudrait aussi désactiver la palette par défaut non ? https://vuetifyjs.com/en/styles/colors/#sass-color-pack

2022-08-08 10:12 UTC, deraw commented on packages/vue-dot/dev/vuetify.ts
> +Object.entries(palette).forEach(color => {
Il faudrait déplacer cela dans Vue Dot pour éviter de le répéter dès qu'on veut configurer les classes non ?

2022-08-08 10:12 UTC, deraw commented on packages/vue-dot/dev/vuetify.ts
> +		const colorName = subColor[0] === 'base' ? 'base' : subColor[0].substring(-20, subColor[0].length - 2) + '-' + subColor[0].substring(subColor[0].length - 2);
Est-ce que ça serait possible de retirer le `base` afin de pouvoir écrire directement `grey--text` par exemple ?

2022-08-08 10:12 UTC, deraw commented on packages/vue-dot/dev/vuetify.ts
> +			dark: colorsClasses
Ici on peut enlever le thème dark pour l'instant ; d'ailleurs ça ne génère pas de classes dupliquées ? 🤔

2022-08-08 10:12 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/types/index.d.ts
> +export interface IndexedObject<T = string> {
Cette interface est déjà présente dans Vue Dot

2022-08-22 12:30 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/slots.vue
> +			<p class="grey--text my-3 mx-4">
Pourquoi avoir remplacé la classe `text--secondary` ?

2022-08-23 14:52 UTC, deraw requested changes
Il manque également ce retour https://github.com/assurance-maladie-digital/design-system/pull/2191#pullrequestreview-1064931409

2022-08-23 14:52 UTC, deraw commented on packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
> +      <p class="text-body-2 lighten-60">
Pourquoi est-ce qu'il n'y a plus le préfixe `text--` ici ?

2022-08-23 14:52 UTC, deraw commented on packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
> +      <p class="text-body-2 lighten-60">
Idem ici pour le préfixe `text--` et la classe de couleur

2022-08-23 14:52 UTC, deraw commented on packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
> +      <p class="text-body-2 lighten-60">
Et d'ailleurs il y a un bug, il manque la classe de la couleur !

2022-08-23 14:52 UTC, deraw commented on packages/form-builder/src/components/FormField/FormField.vue
> +			return 'grey-' + this.$vuetify.theme.dark ? 'lighten-60' : 'base' + '--text';
Est-ce que le `base` est toujours d'actualité ici ?

2022-08-23 14:52 UTC, deraw commented on packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue
> +			return 'grey- ' + this.$vuetify.theme.dark ? 'lighten-60' : 'base' + '--text';
Est-ce que le `base` est toujours d'actualité ici ?

2022-08-23 14:52 UTC, deraw commented on packages/vue-dot/src/patterns/FileUpload/tests/__snapshots__/FileUpload.spec.ts.snap
> +				</span> <span class="mb-2 grey---text">
Attention il y a un triple tiret ici

2022-08-23 14:52 UTC, deraw commented on packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
> +				</span> <span class="mb-2 grey---text">
Attention il y a un triple tiret ici

2022-08-23 14:52 UTC, deraw commented on packages/design-tokens/src/colors.ts
> +export const colorsClasses: IndexedObject = {};
Il ne faudrait exporter la variable après son traitement ? Je pense que ça fonctionne comme mais c'est perturbant dans la lecture non ?

2022-08-23 14:52 UTC, deraw commented on packages/design-tokens/src/colors.ts
> +		const colorName = subColor[0] === 'base' ? '' : subColor[0].substring(-20, subColor[0].length - 2) + '-' + subColor[0].substring(subColor[0].length - 2);
Hum à quoi correspond le `-20` ici ? Est-ce qu'on ne pourrait pas stocker cette valeur dans une constante pour lui donner un nom ?

2022-08-23 14:52 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/plugins/vuetify.ts
> +			light: colorsClasses
Est-ce qu'il y a bien le thème actuel dans cet objet ?

2022-08-23 14:52 UTC, deraw commented on packages/design-tokens/src/colors.ts
> +export const colorsClasses: IndexedObject = {};
Et je pense qu'on peut renommer la variable en `colorClasses`

2022-08-30 12:33 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/plugins/vuetify.ts
> +			light: {
est-ce qu'on peut créer un objet qui merge ces deux là plutôt que de le faire ici ?

2022-08-31 15:24 UTC, deraw approved these changes

2022-08-31 15:24 UTC, deraw approved these changes

2022-08-31 15:33 UTC, merged