update notifications documentation
assurance-maladie-digital/design-system pull request #2237
Opened 2022-08-18 13:39 UTC by Julien-Baylac

## Description

Ajout de la documentation au sujet du systeme de notification.

## Type de changement

- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2022-08-23 09:54 UTC, Kelhel commented on packages/docs/src/content/composants-techniques/module-notification.md
> +});
Tu n'as pas besoin de re-typer la fonction `addNotification`
La fonction `addNotification` n'existe pas par défaut, il faut l'ajouter à la classe via un `mapActions` :

```
<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { mapActions } from 'vuex';

	@Component({
		methods: mapActions('notification', ['addNotification'])
	})
	export default class Home extends Vue {
		sendNotification(): void {
			this.addNotification({
				type: 'success',
				message: 'Exemple de notification'
			});
		}
	}
</script>
```

2022-08-23 09:59 UTC, Kelhel commented
Il faut sans doute faire une partie sur l'import du module en lui meme dans le fichier `src/store/index.ts` pour expliquer comment ce module est ajouté au store de l'application

2022-08-23 10:05 UTC, Kelhel commented on packages/docs/src/data/api/notifications.ts
> +import { Api } from '~/types';
Je pense que tu devrais mettre les api des fonctions `addNotification` et `clearNotification`

2022-08-23 10:17 UTC, Kelhel commented on packages/docs/src/data/api/notifications.ts
> +};
```suggestion
export const api: Api = {
	addNotification: {
		arguments: [
			{
				name: 'notification',
				description: 'Les options de la notifcation.',
				type: 'NotificationObj',
				required: true,
				example: `
type: 'success' | 'error' | 'info' | 'warning';
message: string;
icon?: string;
ref?: string;
				`
			}
		],
		returnValue: [
			{
				type: 'void'
			}
		]
	},
	clearNotification: {
		returnValue: [
			{
				type: 'void'
			}
		]
	}
};
```

2022-08-23 10:22 UTC, Kelhel commented on packages/docs/src/data/drawerItems.ts
>  			}
Est-ce qu'on le mettrais pas dans une catégorie `Store` ?

2022-09-09 15:09 UTC, deraw requested changes

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +Le module de notification sert à gérer les notifications depuis l'ensemble des composants du design system.
```suggestion
```
(la description sert déjà à décrire la fonction du module)

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +description: Module de notification
```suggestion
description: Module Vuex pour afficher des notifications en utilisant le composant [NotificationBar](/composants/feedback/notification-bar).
```

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +<doc-api name="notifications"></doc-api>
Pour moi on peut renommer le fichier `notifications.ts` en `notification-module.ts`

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +		deleteNotification(): void {
On peut ajouter la partie template et utiliser la méthode sur un bouton pour avoir un exemple plus concret

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +### Emettre une notification
```suggestion
### Affichage d’une notification
```

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +Pour émettre une notification, vous pouvez utiliser la fonction `addNotification()` de cette manière :
```suggestion
Vous pouvez utiliser la fonction `addNotification()` pour afficher une notification :
```

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +Le module de notification est déjà importé dans `src/store/index.ts` à la création du projet
```suggestion
Lorsque vous créez un nouveau projet, le module de notification est déjà importé dans le fichier `src/store/index.ts` :
```

2022-09-09 15:09 UTC, deraw commented on packages/docs/src/content/composants-techniques/module-notification.md
> +Pour commencer, il faut importer `NotificationObj` et `NotificationTypes` qui nous servira pour appeler la notification.
Je ne comprends pas ce paragraphe, on importe ces types mais on n'en fait rien, pour moi il faut le supprimer

2022-09-12 14:43 UTC, Julien-Baylac commented on packages/docs/src/data/api/notifications.ts
> +const NotificationTypes = {
Au type de la notification : success, error etc

2022-09-22 13:33 UTC, deraw commented on packages/docs/src/data/api/notifications.ts
> +const NotificationTypes = {
Cette variable n'est pas utilisée

2022-09-23 17:07 UTC, deraw approved these changes

2022-09-23 17:55 UTC, merged