add collapse-list component
assurance-maladie-digital/design-system pull request #2458
Opened 2022-12-13 10:10 UTC by Julien-Baylac

## Description

Ajouter un sous composant de listing pour le Footer

## Playground

```vue
<template>
	<PageContainer>
		<CollapseList :list-items="listItems" />
	</PageContainer>
</template>
<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import CollapseList from '../src/patterns/FooterBar/CollapseList';

	@Component({
		components: {
			CollapseList
		}
	})
	export default class Playground extends Vue {
		listItems = {
			title: 'le titre',
			list: [
				{
					name: 'exemple 1',
					route: '/'
				},
				{
					name: 'exemple 2',
					route: '/'
				},
				{
					name: 'exemple 3',
					route: '/'
				}
			]
		};
	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Refactoring
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-02-17 08:30 UTC, christopheGaon requested changes
la checklist de cette mr n est pas a jour
il n y a pas de modification de la doc associée a la modification de ce composant ?

2023-03-28 12:29 UTC, deraw requested changes

2023-03-28 12:29 UTC, deraw commented on packages/docs/src/content/composants/structure/footer-bar.md
> +#### Liste adaptative
Pourquoi est-ce que cet exemple est dans l'onglet "Personnalisation" ?

2023-03-28 12:29 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapse-list.vue
> +	>
```suggestion
	<FooterBar v-bind="docProps">
```

2023-03-28 12:29 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapse-list.vue
> +
```suggestion
```

2023-03-28 12:29 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapse-list.vue
> +					name: 'Page 3',
Est-ce qu'on pourrait trouver un exemple concret plutôt que "Page 1/2/3" ?

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/tests/CollapseList.spec.ts
> +import CollapseList from '..';
```suggestion
import CollapseList from '../';
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/index.ts
> +import CollapseList from './FooterBar/CollapseList';
Il faut supprimer cette partie, soit le composant est un composant à part entière, soit il faut l'importer comme le `FooterBtn` du `FooterWrapper`.

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/types.d.ts
> +export interface listItem {
```suggestion
export interface ListItem {
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/types.d.ts
> +	list: [];
Il faut typer le contenu de cette liste et trouver un nom plus spécifique pour la propriété

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +
```suggestion
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +		<div v-if="!isMobile">
On pourrait inverse la condition pour éviter la négation qui n'est pas nécessaire ?

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +	<div class="vd-collapse-list my-4">
```suggestion
	<div class="vd-collapse-list">
```
Il ne faut pas appliquer de margin au composant

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +			</div>
Je pense qu'on peut simplifier ce code en ne gardant qu'un élément.
Est-ce que ça ne devrait pas être un titre d'ailleurs ?

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +					target="_blank"
```suggestion
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +					:href="item.route"
```suggestion
					:href="item.href"
```
Avec `route` je m'attends plutôt à un objet à passer à Vue Router

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +			<div
Il faudrait que ce soit une liste

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +			<v-expansion-panels
Il faut utiliser la syntaxe `PascalCase`

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +						<span class="font-weight-bold">
Est-ce qu'on a réellement besoin d'un `span` ici ?

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +						<div
Idem il faut que ce soit une liste

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +								target="_blank"
```suggestion
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +</style>
Ce styles ne sont plus utiles, si ?

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +	import { listItem } from '../CollapseList/types';
```suggestion
	import { listItem } from './types';
```

2023-03-28 12:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapseList/CollapseList.vue
> +	export default class CollapseList extends MixinsDeclaration {
Il faudrait renommer le composant en `CollapsibleList`.

2023-03-28 12:29 UTC, deraw commented on packages/docs/src/content/composants/structure/footer-bar.md
> +Cette liste affiche tout le contenu sur les grands écrans et une liste accordéon sur mobile.
```suggestion
Vous pouvez utiliser le sous-composant `CollapsibleList` pour afficher des listes de liens dans le slot par défaut.
Cette liste affiche tout le contenu sur les grands écrans et une liste accordéon sur mobile.
```

2023-03-28 14:16 UTC, deraw commented
Il faut aussi ajouter le composant au `vueDotLoader`

2023-03-30 19:16 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapsible-list.vue
> +	import CollapsibleList from "@cnamts/vue-dot/src/patterns/FooterBar/CollapsibleList";
```suggestion

	import CollapsibleList from '@cnamts/vue-dot/src/patterns/FooterBar/CollapsibleList';
```

2023-03-30 19:16 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
> +	<VListItem
Quand je parlais de liste je parlais d'éléments `ul` et `li`, par défaut la liste de Vuetify ne génère que des `div`. On pourrait utiliser la prop [tag](https://v2.vuetifyjs.com/en/api/v-list-item/#props-tag) pour changer cela mais on n'a pas besoin de la liste de Vuetify au final

2023-03-30 19:16 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapsible-list.vue
> +				}
```suggestion
					url: 'https://www.ameli.fr/assure/sante/mon-espace-sante'
				},
				{
					name: 'Accomplir les bons gestes',
					url: 'https://www.ameli.fr/assure/sante/bons-gestes'
				},
				{
					name: 'Réagir en cas d’urgence',
					url: 'https://www.ameli.fr/assure/sante/urgence'
				},
				{
					name: 'Télésanté',
					url: 'https://www.ameli.fr/assure/sante/telesante'
				}
```

2023-03-30 19:16 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
> +	<VListItem v-else>
```suggestion

	<VListItem v-else>
```

2023-03-30 19:16 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
> +	content: object[];
Il faut typer de manière plus spécifique ce tableau d'objets, quelles sont les propriétés attendues ?

2023-04-03 15:22 UTC, deraw commented on packages/docs/src/data/examples/footer-bar/collapsible-list.vue
> +					name: 'Réagir en cas d\'urgence',
```suggestion
					name: 'Réagir en cas d’urgence',
```

2023-04-03 15:23 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
> +	content: { name: string; url: string }[];
```suggestion
	content: {
		name: string;
		url: string
	}[];
```

2023-04-03 15:23 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
> +				<VExpansionPanelContent>
```suggestion

				<VExpansionPanelContent>
```

2023-04-03 15:29 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
> +					<li
Ici l'élément `ul` devrait englober la liste

2023-04-03 17:11 UTC, deraw commented on packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
> +		<ul class="pa-0">
```suggestion

		<ul class="pa-0">
```

2023-04-03 17:12 UTC, deraw approved these changes

2023-04-03 17:24 UTC, merged