Feat/#2431 Doc: Page composants
assurance-maladie-digital/design-system pull request #2489
Opened 2023-01-13 09:42 UTC by DavidFyon

## Description

Ajout d'une page de présentation des différents composant de manière graphique

- Nouvelle fonctionnalité
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-03-20 17:19 UTC, deraw commented
On pourrait se baser sur ce qu'à fait Vuetify pour la v3, je trouve ça pas mal https://vuetifyjs.com/en/components/all/

2023-03-21 13:40 UTC, DavidFyon commented
> On pourrait se baser sur ce qu'à fait Vuetify pour la v3, je trouve ça pas mal https://vuetifyjs.com/en/components/all/

c'est un peu ce que j'avais fais mais l'affichage a sauté suite au dernières maj, je vais corriger ça

2023-03-28 11:23 UTC, deraw commented
> @deraw tu peux pliquer ton commentaire , car pour moi c est bueno

Pour moi la page "Vue d'ensemble" ne devrait pas être dans la section "Démarrer", il faudrait la déplacer dans la section "Composants" en page séparée comme dans le menu de la documentation de Vuetify, car c'est une vue d'ensemble des composants et non du Design System. Pareil, je pense qu'il faut supprimer le bouton sticky "Vue d'ensemble" car la page sera présente dans le menu tout le temps.

2023-03-28 11:42 UTC, deraw requested changes

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/components/global/DocStickyButton.vue
> +<template>
On peut supprimer ce composant du coup
Mais si je devais le review : je le verrai plutôt comme un composant spécifique qui ne prendrait pas de props, puisque ça éviterait de passer les mêmes props `icon="view-dashboard" title="Vue d'ensemble" target="../../demarrer/vue-ensemble"` à chaque fois, surtout que ce composant n'est utilisé que pour une seule fonction.

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/content/composants/boutons/back-btn.md
> +<doc-sticky-button icon="view-dashboard" title="Vue d'ensemble" target="../../demarrer/vue-ensemble"></doc-sticky-button>
Idem à supprimer du coup
Et pour implémenter ça je pense que ça aurait été mieux de le faire dans le template qui affiche la page plutôt que dans chaque page

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/drawerItems.ts
> +		title: "Démarrer",
Il faut revert les modifications de formatage

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/images/components/AccessibilityBanner.svg
Est-ce que tu peux passer chaque SVG dans [SVGOMG](https://jakearchibald.github.io/svgomg/) stp ?
Et il faudrait renommer les fichiers en `kebab-case`

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/images/components/CopyBtn.svg
Est-ce que l'icône pourrait être sur la droite ? C'est plutôt comme ça que le composant est utilisé

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/images/components/NirField.svg
Le champ clé doit être à la fin

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/images/templates/ErrorPage.svg
Il faudrait mettre à jour cette image avec une erreur 500

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/content/demarrer/vue-ensemble.md
> +<vue-file file="list-components"></vue-file>
Dans les fichiers Markdown tu peux utiliser des composants Vue directement, c'est ce qu'il faudrait faire ici plutôt que de passer par le composant `VueFile`

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/content/demarrer/vue-ensemble.md
> +# Composants
Il faut que ce soit des titres de niveau 2, le nom de la page est le titre de niveau 1 (et il n'en faut qu'un seul par page)

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/examples/list-components.vue
> +					<nuxt-link to="../composants/structure/header-bar">
Pourquoi ne pas utiliser un tableau de données ?

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/examples/list-components.vue
> +		<v-container class="mb-10">
Le `VContainer` ajoute un padding qu'il faudrait enlever

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/examples/list-components.vue
> +	}
Pourquoi autant de CSS, est-ce qu'on ne pourrait pas utiliser les classes utilitaires de Vuetify ?

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/examples/list-templates.vue
> +<template>
On peut fusionner ce composant avec le précédent, c'est juste un tableau de données différent

2023-03-28 11:42 UTC, deraw commented on packages/docs/src/data/examples/list-components.vue
> +		<v-divider></v-divider>
Il faut utiliser la syntaxe `PascalCase` pour les composants

2023-04-05 13:54 UTC, DavidFyon commented on packages/docs/src/content/demarrer/vue-ensemble.md
> +<vue-file file="list-components"></vue-file>
Je n'ai pas réussi à mettre le composant directement

2023-04-05 14:39 UTC, DavidFyon commented on packages/docs/src/components/global/DocStickyButton.vue
> +<template>
je ne vois pas trop comment intégrer le composant directement dans le markdown

2023-04-05 15:09 UTC, deraw commented on packages/docs/src/content/demarrer/vue-ensemble.md
> +<vue-file file="list-components"></vue-file>
Tu peux regarder dans la page [`couleurs.md`](https://raw.githubusercontent.com/assurance-maladie-digital/design-system/dev/packages/docs/src/content/fondamentaux/couleurs.md) pour un exemple, la syntaxe est un peu différente et il faut que le composant soit dans le dossier `global` pour que ça fonctionne

2023-04-05 15:21 UTC, deraw commented on packages/docs/src/data/examples/list-components.vue
> +					<nuxt-link to="../composants/structure/header-bar">
En fait je parlais d'un tableau JS pour éviter de répéter le même markup, du genre :
```ts
const componentList = [
	{
		title: 'Structure',
		components: [
			{
				name: 'HeaderBar',
				description: 'Utilisé pour afficher l’en-tête d’une page ainsi qu’une barre de navigation.',
				href: '/composants/structure/sub-header',
				image: 'components/header-bar.svg'
			}
		]
	}
];
```
(et en vrai on pourrait générer les deux derniers éléments automatiquement mais c'est déjà bien)

2023-04-07 08:22 UTC, DavidFyon commented on packages/docs/src/components/global/DocStickyButton.vue
> +<template>
L'avantage du composant est qu'il est réutilisable et rend le md plus lisible. 
Une utilisation que je vois pourrait être sur cette page : http://localhost:3000/demarrer/contribuer avec un bouton "Rapporter un bug" qui serait plus visible qu'un simple lien.

2023-04-11 12:50 UTC, christopheGaon approved these changes

2023-04-11 12:50 UTC, christopheGaon commented on packages/docs/src/components/global/DocStickyButton.vue
> +<template>
si je comprends bien ce serait un composant pas du desisgn system mais de la doc , ok pour tout le monde ?

2023-04-12 20:00 UTC, deraw approved these changes

2023-04-12 20:22 UTC, merged