Menu contextuel
assurance-maladie-digital/design-system pull request #2572
Opened 2023-03-09 15:02 UTC by Julien-Baylac

## Description

Ajouter le composant ContextualMenu

## Playground

<details>

```vue
<template>
	<PageContainer>
		<ContextualMenu
			:tabs="tabs"
			@current-tab="changeTab"
		/>
	</PageContainer>
</template>
<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';
	import ContextualMenu from '../src/patterns/ContextualMenu';

	@Component({
		components: {
			ContextualMenu
		}
	})
	export default class Playground extends Vue {
		currentTab = '';

		tabs = [
			{
				name: 'Onglet 1',
				label: 'Onglet 1',
				route: '1'
			},
			{
				name: 'Onglet 2',
				label: 'Onglet 1',
				route: '2'
			},
			{
				name: 'onglet 3',
				label: 'Onglet 1',
				route: '3'
			},
			{
				name: 'onglet 4',
				label: 'Onglet 1',
				route: '4'
			},
			{
				name: 'onglet 5',
				label: 'Onglet 1',
				route: '5'
			}
		];

		changeTab(newTab: string): void {
			this.currentTab = newTab;
		}
	}
</script>

```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-04 18:03 UTC, deraw requested changes

2023-04-04 18:03 UTC, deraw commented on packages/docs/src/data/examples/contextual-menu/base.vue
> +		Current tab : {{ currentTab }}
Je pense qu'on peut enlever le `PageContainer` et le texte d'exemple

2023-04-04 18:03 UTC, deraw commented on packages/docs/src/data/examples/contextual-menu/base.vue
> +	export default class Playground extends Vue {
```suggestion
	export default class ContextualMenuUsage extends Vue {
```

2023-04-07 14:28 UTC, Julien-Baylac commented on packages/docs/src/data/api/contextual-menu.ts
> +				required: true,
Je met quelque chose comme : "Onglet 1, Onglet 2" par défaut sur la props, et je retire le required ?

2023-04-07 14:40 UTC, Julien-Baylac commented on packages/docs/src/data/api/contextual-menu.ts
> +	name: 'onglet-1',
C'était au cas ou il y avait un doublon dans les routes ou les labels ici :key="tab.name"
Je remplace par le label

2023-04-07 16:02 UTC, Julien-Baylac commented on packages/vue-dot/src/patterns/ContextualMenu/ContextualMenu.vue
> +		activeTab = this.tabs.length ? this.tabs[0] : { route: '' };
Pour que l'element actif soit le premier par défaut quand on arrive sur la page. Mais je peux changer

2023-04-07 18:28 UTC, deraw commented on packages/vue-dot/src/patterns/ContextualMenu/ContextualMenu.vue
> +		activeTab = this.tabs.length ? this.tabs[0] : { route: '' };
Je veux bien parce que ce n'est pas forcément le comportement voulu

2023-04-13 18:28 UTC, deraw approved these changes

2023-04-13 18:39 UTC, merged