Feature/rating component wrapper
assurance-maladie-digital/design-system pull request #2659
Opened 2023-03-24 16:44 UTC by christopheGaon

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici

<template>
	<PageContainer>
		
		<stars-picker
			label="ou aller vous cherchez tout ca ?"
			:length="26"
			@input="onValidate"
		/>
		<number-picker
			label="ou aller vous cherchez tout ca ?"
			:length="26"
			@input="onValidate"
		/>
		<rating-picker
			label="ca va ?"
			type="NumberPicker"
		>
			<FormField v-model="field" />
		</rating-picker>
		<rating-picker
			label="ca va ?"
			type="NumberPicker"
		>
			<FormField v-model="field1" />
		</rating-picker>
	</PageContainer>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';
	import StarsPicker from '../src/patterns/RatingPicker/StarsPicker';
	import EmotionPicker from '../src/patterns/RatingPicker/EmotionPicker';
	import NumberPicker from '../src/patterns/RatingPicker/NumberPicker/NumberPicker.vue';
	import { RatingMixin } from '../src/patterns/RatingPicker/RatingMixin';
	import RatingPicker from '../src/patterns/RatingPicker/RatingPicker.vue';
	import { Field } from '@cnamts/form-builder/src/components/FormField/types';

	@Component({
		components: { RatingPicker, NumberPicker, EmotionPicker,StarsPicker }
	})
	export default class Playground extends Vue {
		field: Field = {
			type: 'textarea',
			title: 'Vos symptômes',
			value: null,
			fieldOptions: {
				hideDetails: true,
				outlined: true
			}
		};

		field1: Field = {
			type: 'select',
			title: 'ca veut dire quoi acab ?',
			items: [
				{
					text: 'Email',
					value: 'email'
				},
				{
					text: 'Courrier',
					value: 'mail'
				},
				{
					text: 'SMS',
					value: 'sms'
				}
			],
			value: null,
			fieldOptions: {
				type: 'choiceButton',
				label: 'Moyen de contact',
				hideDetails: true,
				outlined: true
			}
		};
		onValidate(event: RatingMixin, value: number): void {
			event.blockon(value);
		}
	}
</script>

```

</details>

## Type de changement

- Refactoring
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-04 16:03 UTC, deraw requested changes

2023-04-04 16:03 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +		expect(wrapper.vm.getitemLabel(-1)).toBe('');
On pourrait pas utiliser une snapshot pour ça plutôt ?

2023-04-05 09:06 UTC, christopheGaon commented on packages/vue-dot/src/patterns/RatingPicker/NumberPicker/tests/__snapshots__/NumberPicker.spec.ts.snap
> +exports['NumberPicker renders correctly 1'] = `
oui c est la qual qui fait ca , je vais regenerer les specs pour killer ca

2023-04-05 09:07 UTC, christopheGaon commented on packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
> +		}
c est pour afficher le label au debut et a la fin, je vais rajouter des commenst sur l utilisation de cette fonction

2023-04-05 09:09 UTC, christopheGaon commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +		expect(wrapper.vm.getitemLabel(-1)).toBe('');
la on test la methode getitemLabel plutot que le template

2023-04-05 09:35 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
> +		}
:+1: tu peux aussi renommer la variable 😇

2023-04-05 12:38 UTC, christopheGaon commented on packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
> +			);
oui donc comme convenu on utilise le slot avec un onmouseover et onfocus pour gerer ca

2023-04-05 13:27 UTC, christopheGaon commented on packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
> +				type: Array<string>,
ca genere ce genre d erreur 

`'string' only refers to a type, but is being used as a value here.`

2023-04-05 16:50 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
> +		getitemLabel(value: number): string {
```suggestion
		getItemLabel(value: number): string {
```

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/tests/EmotionPicker.spec.ts
> +				label: 'Label test',
```suggestion
				label: 'Pourriez-vous donner une note ?',
```

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
> +					<div />
Est-ce que cette `div` est utile ?

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
> +			// on laisse a chaque rating le soin de decider comment il se bloque
```suggestion
```

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +				length: undefined
```suggestion
				label: 'Pouvez-vous nous en dire plus ?'
```

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +				itemLabels: ['label1','label2','label3']
Il faudrait des labels plus "réalistes" comme dans les autres tests

2023-04-07 15:44 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +	it('block on', async() => {
à mettre à jour

2023-04-07 15:45 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
> +				type: Array<string>,
j'ai mis à jour la suggestion

2023-04-11 15:39 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +const itemLabels = ['non je dis rien','faut voir','je dirais tout ce que vous voulez'];
```suggestion
const label = 'Pouvez-vous nous en dire plus ?';
const itemLabels = [
	'Non je dis rien',
	'Faut voir',
	'Je dirais tout ce que vous voulez'
];
```
Et est-ce que tu peux les déplacer dans le bloc `describe` stp ?

2023-04-11 15:39 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +	it('verify props', () => {
```suggestion
	it('verifies props', () => {
```

2023-04-11 15:39 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +	it('verify itemLabels', () => {
```suggestion
	it('verifies item labels', () => {
```

2023-04-11 15:39 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +	it('dispatch event', async() => {
```suggestion
	it('dispatch input event', async() => {
```

2023-04-11 15:39 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/tests/RatingMixin.spec.ts
> +	it('lockField on', async() => {
```suggestion
	it('locks field', async() => {
```

2023-04-21 16:43 UTC, merged