Ajout des pages maintenance and not-found
assurance-maladie-digital/design-system pull request #2687
Opened 2023-04-05 14:39 UTC by Julien-Baylac

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-06 10:08 UTC, christopheGaon requested changes
https://github.com/assurance-maladie-digital/vue-dash/blob/master/src/template/src/views/NotFound.vue normalement y a que ce fichier a modifier dans ta pr a priori

2023-04-06 10:08 UTC, christopheGaon commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
normalement tu as pas a changer ce fichier

2023-04-06 10:08 UTC, christopheGaon commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
normalement tu as pas a changer ce fichier

2023-04-06 16:09 UTC, deraw requested changes

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/public/maintenance.svg
Le fichier est à supprimer

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/public/not-found.svg
Le fichier est à supprimer

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/views/notFound.ts
> -	},
Il faut garder ces traductions car ce sont le titre et la description de la page

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
> +	<MaintenancePage/>
```suggestion
	<MaintenancePage />
```

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
> +	import MaintenancePage from '../components/MaintenancePage'
Le composant est importé automatiquement avec le Vue Dot Loader, pas besoin de l'importer

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
> -			};
Il faut garder cette partie car ce sont les informations de la page

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/MaintenancePage/MaintenancePage.vue
Le fichier et ceux associés sont à supprimer, le composant existe déjà dans Vue Dot

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/MaintenancePage/locales.ts
> -	title: 'Maintenance en cours',
à revert

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
> +	<NotFoundPage/>
```suggestion
	<NotFoundPage />
```

2023-04-06 16:09 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
> +	export default class NotFound extends Vue {}
Mêmes remarques que pour la page de maintenance

2023-04-07 14:27 UTC, deraw approved these changes

2023-04-07 14:44 UTC, merged