Vue-dot: add slots on notification bar
assurance-maladie-digital/design-system pull request #2704
Opened 2023-04-12 13:57 UTC by DavidFyon

## Description

En tant qu'utilisateur je dois pouvoir visualiser une snackbar ou notifications bar répondant à une nouvelle condition :

Avoir une zone d'interaction dédiée avec un bouton de lien de type secondary et un icône d'action pour fermer ou recharger la page et/ou la zone interactive.
Avoir une version desktop et une version mobile (+ ajout maquette Figma)

## Playground

<details>

```vue
<template>
	<div>
		<NotificationBar v-show="showNotificationBar">
			<template #divider>
				<svg
					width="1"
					height="36"
					role="img"
					focusable="false"
					aria-hidden="true"
					class="ml-3"
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 1 36"
				>
					<path :stroke="textColor" d="M.5 36V0"/>
				</svg>
			</template>

			<template #actions>
				<VBtn
					color="white"
					class="mr-3"
					elevation="0"
					outlined
				>
					Bouton
				</VBtn>
				<VBtn
					color="white"
					class="mr-3"
					elevation="0"
					text
				>
					Bouton
				</VBtn>
				<VBtn
					color="primary"
					@click="clearNotification"
				>
					Fermer
				</VBtn>
			</template>
		</NotificationBar>

		<VBtn
			color="primary"
			@click="notifyUser"
		>
			Envoyer une notification
		</VBtn>
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { mapActions, mapState } from 'vuex';

	const EXAMPLE_REF = 'usage-example';

	@Component({
		computed: mapState('notification', ['notification']),
		methods: mapActions('notification', ['addNotification'])
	})
	export default class NotificationBarUsage extends Vue {
		get showNotificationBar(): boolean {
			return this.notification?.ref === EXAMPLE_REF;
		}

		notifyUser(): void {
			this.addNotification({
				ref: EXAMPLE_REF,
				type: 'info',
				message: 'Exemple de notification.'
			});
		}

		clearNotification(): void {
			this.notification?.ref = '';
		}

		get textColor(): string {
			const isSuccess = this.notification?.type === 'success';
			const isWarning = this.notification?.type === 'warning';

			if (isSuccess || isWarning) {
				return 'grey-darken-80';
			}

			return 'white';
		}
	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-20 17:00 UTC, deraw requested changes
Il faudrait que tu vois avec @Becqueva, ce qu'on s'est dit c'est que le divider apparaissaît si le slot avait du contenu, et que l'affichage vertical en mobile s'activait si le slot avait du contenu ou si le message était supérieur à une certaine longueur
Et finalement le slot ne permet que d'ajouter du contenu, pas de remplacer le bouton Fermer
[Les maquettes](https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/DS-CNAM---WIP-Composants?node-id=509-6780&t=IPc4NLxh3PoCEKyE-0) sont à jour avec ce fonctionnement

2023-05-15 15:24 UTC, christopheGaon commented on packages/docs/src/data/examples/notification-bar/slot.vue
il faudrait que le nom de la classe et le nom du fichier colle

2023-05-15 15:24 UTC, christopheGaon commented on packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
> +	}
on est vraiment obliger de sortir autant des sentiers battus, niveau css ? @Becqueva

2023-05-15 15:24 UTC, christopheGaon commented on packages/docs/src/data/examples/notification-bar/slot.vue
> +				ref: EXAMPLE_REF,
cette ref , fait reference a quoi ? la notification bar du template de base de la doc ?

2023-05-15 15:39 UTC, christopheGaon commented on packages/docs/src/data/examples/notification-bar/slot.vue
> +				ref: EXAMPLE_REF,
c est pas une ref au sens html , ni vue, mais plus un id

2023-05-15 15:42 UTC, christopheGaon approved these changes

2023-05-17 18:38 UTC, deraw approved these changes

2023-05-17 18:47 UTC, merged