WIP vue-dot: Ajouter des slots au composant HeaderBar
assurance-maladie-digital/design-system pull request #2723
Opened 2023-04-19 09:51 UTC by DavidFyon

## Description

Ajouter le slot navigation-drawer-seconday-content au composant HeaderBar, pour pouvoir ajouter des composants spécifiques.

## Playground

<details>

```vue
<template>
	<HeaderBar
		:navigation-items="navigationItems"
		:show-nav-bar-menu-btn="false"
	>
		<template #navigation-bar-secondary-content>
			<div class="d-flex align-center justify-center">
				<VBtn color="primary">
					Se connecter
				</VBtn>
			</div>
		</template>
		<template #navigation-drawer-secondary-content>
			<div class="d-flex align-center justify-center">
				<VBtn
					color="primary"
					block
				>
					Se connecter
				</VBtn>
			</div>
		</template>
	</HeaderBar>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { NavigationItem } from '@cnamts/vue-dot/src/patterns/HeaderBar/types';

	@Component
	export default class HeaderBarNavigationBar extends Vue {
		navigationItems: NavigationItem[] = [
			{
				label: 'Accueil'
			},
			{
				label: 'Mes projets'
			},
			{
				label: 'Mes outils'
			}
		];
	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-20 17:13 UTC, deraw requested changes

2023-04-24 07:19 UTC, DavidFyon commented on packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
> +	}
Pour positionner les éléments mis en append toujours en bas de la navigation

2023-04-24 07:57 UTC, DavidFyon commented on packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
> +				<slot name="navigation-drawer-content-prepend" />
il serait peux être mieux d'harmoniser les noms entre les composants pour s'y retrouver ? :
- navigation-bar-prepend
- navigation-drawer-prepend
- navigation-drawer-append

2023-05-15 14:44 UTC, christopheGaon approved these changes
en dehors des question, sur le fond c est ok pour moi

2023-05-15 14:44 UTC, christopheGaon commented on packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
> +	}
il y aurait pas moyen de faire du flex plutot

2023-05-15 14:44 UTC, christopheGaon commented on packages/docs/src/data/examples/header-bar/slot-drawer.vue
> +					Se connecter
juste mettre un titre qui fait reference a prepend ou append pour expliciter le positionnement

2023-05-15 14:44 UTC, christopheGaon commented on packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue
> +				<slot name="navigation-drawer-content-prepend" />
en effet la nomenclature c est compliqué, peut etre un truc comme ca mais franchement c est le template qui rend le nommage compliqué

https://medium.com/js-dojo/vue-named-slot-shorthand-8a920358e861

2023-05-16 15:15 UTC, deraw approved these changes

2023-05-16 15:24 UTC, merged