Remove font loader
assurance-maladie-digital/design-system pull request #2737
Opened 2023-04-21 15:02 UTC by Julien-Baylac

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-05-04 08:48 UTC, DavidFyon commented on packages/vue-cli-plugin-vue-dash/generator/template/public/css/base.css
> +	font-family: 'Source Sans Pro'
Il faut laisser le sans-serif non ?

2023-05-16 15:41 UTC, deraw requested changes

2023-05-16 15:41 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/public/css/base.css
> +	font-family: 'Source Sans Pro'
Oui il faut même revert complètement cette modif

2023-05-16 15:41 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_Pro/OFL.txt
> +Copyright 2010, 2012, 2014 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name ‘Source’.
Est-ce qu'on est obligés d'ajouter cette licence ? Est-ce qu'on doit également la référencer dans le Readme ou quelque part ?

2023-05-16 15:41 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/style.scss
> +@font-face {
Ici on ne définit qu'un seul style de police alors qu'on ajoute plein de fichiers pour des styles différents, il faut utiliser les fichiers dont on a besoin pour définir les styles correspondants et supprimer ceux qu'on n'utilise pas.

Au niveau format je pense qu'on peut aussi ajouter le WOFF2 pour améliorer les performances

2023-05-17 14:36 UTC, deraw commented
Il faudrait également ajouter cette police dans la documentation 👀

2023-05-24 15:06 UTC, DavidFyon commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/fonts/Source_Sans_Pro/OFL.txt
> +Copyright 2010, 2012, 2014 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name ‘Source’.
Je pense que la licence est obligatoire mais elle peux être à la racine du projet avec les autres.

2023-05-26 16:48 UTC, christopheGaon requested changes
on y presque

2023-05-26 16:48 UTC, christopheGaon commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/style.scss
> +	url(./fonts/Source_Sans_Pro/SourceSansPro-Regular.woff2) format("woff2");
est ce qu on doit ajouter la bold ou l italique ?

2023-05-26 16:48 UTC, christopheGaon commented on packages/vue-dot/src/styles/vuetify.scss
> -		font-family: 'Mic 32 New', 'Source Sans Pro', 'Open Sans', sans-serif !important;
il faut sans doute remettre ca sinon ceux qui utilisent la Mic32New ne pourront plus l utiliser ?

2023-05-26 16:53 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/style.scss
> +@font-face {
Avec les deux formats comme cela :
```css
@font-face {
	font-family: 'source_sans_proregular';
	src:
		url('sourcesanspro-regular-webfont.woff2') format('woff2'),
		url('sourcesanspro-regular-webfont.woff') format('woff');
	font-weight: normal;
	font-style: normal;
}
```

2023-05-30 08:19 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/styles/style.scss
> +	url(./fonts/Source_Sans_Pro/SourceSansPro-Regular.woff2) format("woff2");
En fait le navigateur va construire une police en gras ou en italique à partir du style normal, mais le design de la police est différent en fonction des styles parce que ce ne sont pas les mêmes contraintes
Du coup ce que va générer le navigateur est différent de ce qui a été désigné et ça a été désigné d'une certaine façon pour que ce soit plus lisible etc

2023-05-30 12:41 UTC, deraw commented on packages/vue-dot/src/styles/variables.scss
> -$heading-font-family: 'Mic 32 New', 'Source Sans Pro', sans-serif;
ce sont des variables globales de Vuetify non ?

2023-05-30 13:42 UTC, deraw commented on packages/vue-dot/src/styles/vuetify.scss
> -		font-family: 'Mic 32 New', 'Source Sans Pro', 'Open Sans', sans-serif !important;
Non ce n'est pas bon !
`Open Sans` c'est la police installée et utilisée actuellement. On modifie cela pour que `Source Sans Pro` soit la police installée et utilisée par défaut, elle prend la priorité sur `Open Sans`. Si la police `Mic 32 New` est installée, elle doit prendre la priorité sur toutes les autres.

On ne doit pas installer `Open Sans` par défaut

2023-05-30 13:42 UTC, deraw commented on packages/vue-dot/src/styles/vuetify.scss
>  	}
```suggestion
		font-family: 'Mic 32 New', 'Source Sans Pro', 'Open Sans', sans-serif !important;
	}

```

2023-05-30 13:45 UTC, deraw commented
Il faudrait aussi voir pour utiliser cette police dans la documentation, mais peut-être sur une autre PR

2023-05-31 07:23 UTC, DavidFyon commented
> Il faudrait aussi voir pour utiliser cette police dans la documentation, mais peut-être sur une autre PR

Oui car en mettant la Source Sans Pro il va falloir changer également peux-être certaines tailles (menus, titres...).

Open Sans :
![Capture d’écran 2023-05-31 à 09 21 22](https://github.com/assurance-maladie-digital/design-system/assets/1822420/7bbd714c-e68c-4a3a-b8b9-1be80e8a6aa3)

Source Sans Pro :
![Capture d’écran 2023-05-31 à 09 21 12](https://github.com/assurance-maladie-digital/design-system/assets/1822420/5a47609d-cd0c-421c-b0fa-4a311259ed26)

2023-06-05 08:48 UTC, christopheGaon approved these changes
on fait la doc dans une autre PR comme convenu en equipe

2023-06-13 14:17 UTC, deraw approved these changes

2023-06-13 14:21 UTC, merged