add mobileVersion prop
assurance-maladie-digital/design-system pull request #2756
Opened 2023-04-25 12:31 UTC by DavidFyon

## Description

Ajouter la prop mobile-version au composant UserMenuBtn #2616

## Playground

<details>

```vue
<template>
	<UserMenuBtn full-name="Édith Cartier">
		<VListItem
			v-for="(item, index) in items"
			:key="index"
		>
			<VListItemTitle>{{ item }}</VListItemTitle>
		</VListItem>
	</UserMenuBtn>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class UserMenuBtnDefaultSlot extends Vue {
		items = [
			'Administration',
			'Profil',
			'Paramètres'
		];
	}
</script>
```

</details>

## Type de changement

- Maintenance

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-04-26 09:25 UTC, DavidFyon commented
Si le but est d'afficher le composant UserMenuBtn dans la navigation mobile, cela sera possible avec l'ajout des slots sur le HeaderBar avec quelque chose du genre :

`<template>
	<HeaderBar :navigation-items="navigationItems">
		<UserMenuBtn
			full-name="Édith Cartier"
			v-if="!isMobileVersion"
		>
			<VListItem
				v-for="(item, index) in items"
				:key="index"
			>
				<VListItemTitle>{{ item }}</VListItemTitle>
			</VListItem>
		</UserMenuBtn>
		<template #navigation-drawer-content>
			<UserMenuBtn full-name="Édith Cartier">
				<VListItem
					v-for="(item, index) in items"
					:key="index"
				>
					<VListItemTitle>{{ item }}</VListItemTitle>
				</VListItem>
			</UserMenuBtn>
		</template>
	</HeaderBar>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { NavigationItem } from '@cnamts/vue-dot/src/patterns/HeaderBar/types';

	@Component
	export default class HeaderBarDefaultSlot extends Vue {
		mobileVersion = false;
		navigationItems: NavigationItem[] = [
			{
				label: 'Accueil'
			},
			{
				label: 'Mes projets'
			},
			{
				label: 'Mes outils'
			}
		];

		items = [
			'Profil',
			'Paramètres',
			'Administration'
		];

		get isMobileVersion(): boolean {
			if (this.mobileVersion) {
				return true;
			}

			return this.$vuetify.breakpoint.smAndDown;
		}
	}
	</script>
`

2023-05-17 15:03 UTC, deraw commented
> Si le but est d'afficher le composant UserMenuBtn dans la navigation mobile, cela sera possible avec l'ajout des slots sur le HeaderBar.

En fait le but c'est de masquer les infos à gauche de l'icône lorsque la prop est présente, actuellement il faut enlever le texte manuellement pour le faire

2023-06-08 15:16 UTC, deraw commented
@DavidFyon tu peux ajouter la prop dans l'exemple `usage.vue` stp ?

2023-06-08 16:03 UTC, deraw requested changes

2023-06-09 10:52 UTC, DavidFyon commented
@deraw @christopheGaon  j'ai ajouter une prop list-left pour pouvoir palier si besoin à ce genre de problème d'affichage :

![Capture d’écran 2023-06-09 à 12 23 03](https://github.com/assurance-maladie-digital/design-system/assets/1822420/cbf34482-e64f-47a1-a3b6-fb6b05e14fbe)

2023-06-13 17:16 UTC, deraw requested changes

2023-06-13 17:16 UTC, deraw commented on packages/vue-dot/src/elements/UserMenuBtn/UserMenuBtn.vue
>  				<VBtn
Il faudrait ajouter `:disabled="!hasListContent"` pour que le menu ne s'ouvre pas s'il n'y a pas de contenu (actuellement il reste une ombre même s'il n'y a pas de contenu)

2023-06-13 17:16 UTC, deraw commented on packages/docs/src/data/api/user-menu-btn.ts
> +			},
Je pense qu'on peut supprimer cette prop et le CSS associé à la position du menu, à mon avis il y a moyen d'utiliser les props Vuetify (qui gère le repositionnement automatique s'il n'y a pas la place), sinon on laisse la position par défaut

2023-06-15 15:12 UTC, deraw approved these changes

2023-06-15 15:22 UTC, merged