vue-dot: Améliorer l'accessibilité du RatingPicker
assurance-maladie-digital/design-system pull request #2795
Opened 2023-05-09 14:02 UTC by DavidFyon

## Description

Actuellement les composants rating utilisent des boutons avec un attribut aria-label.
Cela n'est pas suffisant pour l'accessibilité car il manque des contrôles (navigation avec les flèches notamment), que la valeur sélectionné n'est pas indiquée (les boutons n'ont pas d'attribut aria-pressed) et que ces champs de formulaire ne sont pas identifiés comme tels.

Il faut revoir la sémantique implémentée en utilisant des inputs de type radio masqués (comme démontré sur l'exemple [Rating Radio Group](https://www.w3.org/WAI/ARIA/apg/patterns/radio/) du W3C).

## Playground

<details>

```vue
<template>
	<PageContainer>
		<RatingPicker
			label="Êtes-vous satisfait de ce service ?"
			type="emotion"
		/>
	</PageContainer>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {}
</script>
```

</details>

## Type de changement

- Maintenance

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-05-10 15:55 UTC, DavidFyon commented
NB : j'ai du réécrire le starPicker pour le rendre accessible

2023-05-16 15:32 UTC, deraw requested changes
Il faut utiliser la prop `tag` sur les composants `VBtn` à l'intérieur des `labels` pour que ce ne soit pas des boutons car ce n'est pas accessible d'ajouter un élément interactif dans une balise `label`

Aussi pourquoi ne pas utiliser un combo `label` et `input` natif à la place du `VRadio` ? Cela éviterait de devoir écraser les styles

2023-05-16 15:32 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
Il a y des différences de comportement entre ta version et dev

2023-05-16 15:32 UTC, deraw commented on packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
> +								@focusout="hoverValue = -1"
Ces interactions devraient être au niveau du label

2023-06-01 18:57 UTC, deraw approved these changes

2023-06-01 19:10 UTC, deraw commented
@assurance-maladie-digital/front 

Après revue, le fait d'utiliser une sémantique avec des boutons radio pour les composants rating ne convient pas. En effet, le composant utilisé se désactive une fois une valeur sélectionnée, là où les boutons radio nécessitent de pouvoir naviguer en modifiant la valeur pour sélectionner la valeur souhaitée.
(Par exemple, avec un type `emotion`, une fois que le composant recevait le focus, le premier élément était sélectionné, mais en parcourant les valeurs avec les flèches, le composant se désactivait et l'utilisateur se retrouvait bloqué)

Bien que non idéale, la solution implémentée est de garder les boutons mais d'ajouter les bons attributs dessus (`aria-pressed`, `disabled`) et de standardiser le comportement pour que le composant se désactive une fois une valeur sélectionnée, même s'il est utilisé en dehors du `RatingPicker`.

J'ai aussi corrigé l'état `readonly` du composant `NumberPicker` car il s'affichait en mode "valeur sélectionnée" avec `-1` d'affiché quand aucune valeur n'était définie au lieu d'afficher le mode "sélection" mais désactivé. J'ai aussi corrigé ce qui était annoncé pour le résultat pour les lecteurs d'écran afin de simplifier et de ne pas avoir le détail de l'implémentation (dire que c'est un bouton désactivé avec telle valeur, puis la note maximale possible).

2023-06-01 19:10 UTC, merged