Doc : add Source Sans Pro font
assurance-maladie-digital/design-system pull request #2842
Opened 2023-05-31 11:59 UTC by DavidFyon

## Description

Change Open Sans to Source Sans Pro

</details>

## Type de changement

- Maintenance

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-05-31 12:16 UTC, DavidFyon commented
En passant la doc en Source Sans Pro tout paraît plus petit.

Open Sans :
![Capture d’écran 2023-05-31 à 14 09 46](https://github.com/assurance-maladie-digital/design-system/assets/1822420/c9f6114a-61f4-4ae2-80df-c330cceb4033)

Source Sans Pro :
![Capture d’écran 2023-05-31 à 14 09 39](https://github.com/assurance-maladie-digital/design-system/assets/1822420/26254a04-3f41-45e7-ba5d-7082b6122800)

2023-06-07 16:08 UTC, christopheGaon approved these changes

2023-06-07 16:08 UTC, christopheGaon commented on packages/docs/nuxt.config.js
> +			'Source+Sans+Pro': [300, 400, 600, 700],
vu avec @deraw il y a un soucis avec a 500 qui est utilisé par dafaut pas plusieur composant.
Laquelle prend t il en ce cas ?

2023-06-09 08:22 UTC, DavidFyon commented
@deraw j'intègre du coup la Source Sans 3 dans le projet ? le plugin nuxt/google-font n'intègre pas la Source Sans 3

2023-06-13 16:35 UTC, deraw commented
> @deraw j'intègre du coup la Source Sans 3 dans la doc ? le plugin nuxt/google-font n'intègre pas la Source Sans 3

Le plugin utilise directement l'API de Google, elle est bien présente chez moi (et le mieux c'est de setter l'option `download` à `true`)

2023-06-15 15:17 UTC, deraw requested changes

2023-06-15 15:17 UTC, deraw commented on packages/docs/nuxt.config.js
> +			'Open+Sans': [300, 400, 500, 600, 700]
Il faut supprimer ces deux polices, elles ne sont plus utilisées

2023-06-15 15:17 UTC, deraw commented on packages/docs/src/assets/css/fonts.css
Est-ce qu'on peut faire du nettoyage et ne garder que ce qu'on utilise ?
Pas vraiment besoin des polices pour le Cyrillique par exemple

2023-06-15 15:17 UTC, deraw commented on packages/docs/src/assets/styles/typography/global.scss
> +	}
à supprimer

2023-06-16 07:34 UTC, DavidFyon commented on packages/docs/src/assets/styles/base.scss
> +	font-family: 'Source Sans 3', 'Source Sans Pro', 'Open Sans', sans-serif;
Est-ce que j'enlève Source Sans Pro et Open Sans du coup ?

2023-06-16 11:44 UTC, deraw commented on packages/docs/src/assets/styles/base.scss
> +	font-family: 'Source Sans 3', 'Source Sans Pro', 'Open Sans', sans-serif;
Yep en effet c'est plus nécessaire

2023-06-16 15:47 UTC, deraw approved these changes

2023-06-16 16:19 UTC, merged