Doc : add matchPattern rule
assurance-maladie-digital/design-system pull request #2855
Opened 2023-06-05 11:32 UTC by DavidFyon

## Description

Ajouter la règle de validation matchPatternFn (https://github.com/assurance-maladie-digital/design-system/issues/2608)

## Type de changement

- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-06-07 16:17 UTC, deraw requested changes

2023-06-07 16:17 UTC, deraw commented on packages/docs/src/data/drawerItems.ts
Il ne devrait pas y avoir autant de différences sur ce fichier, si ?

2023-06-07 16:17 UTC, deraw commented on packages/docs/src/data/api/rules/match-pattern.ts
> +			},
```suggestion
			},
```
La fonction `ruleMessage` génère cette prop

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/locales.ts
> +	default: 'Le format saisi ne correspond pas.'
```suggestion
	default: 'Le format saisi ne correspond pas au format attendu.'
```

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/locales.ts
> +export const defaultErrorMessages: ErrorMessages<number> = {
```suggestion
export const defaultErrorMessages: ErrorMessages = {
```

2023-06-07 16:17 UTC, deraw commented on packages/docs/src/data/api/rules/match-pattern.ts
> +			}`)
```suggestion
	default: 'Le format saisi ne correspond pas au format attendu.',
}`)
```
il faut absolument faire attention à l'indentation du code ici car vu qu'on utilise des templates literals, tous les caractères sont inclus dans la chaîne, du coup l'affichage n'est pas bon dans la documentation

![screenshot-647dc9ecb5874007a05dbf4a--digital-design-system netlify app-2023 06 07-18_09_55](https://github.com/assurance-maladie-digital/design-system/assets/10298932/60a12497-9203-4fa8-a2c4-d1dc689f9291)

2023-06-07 16:17 UTC, deraw commented on packages/docs/src/data/api/rules/match-pattern.ts
> +				description: 'Le motif à respecter.'
```suggestion
				description: 'L’expression régulière permettant de valider la valeur.'
```

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
> +		expect(validator('')).toBe(true);
```suggestion
		const rule = matchPattern(/^[A-Z]+$/);

		expect(rule('')).toBe(true);
```

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
> +		expect(validator('ABC')).toBe(true);
```suggestion
		const rule = matchPattern(/^[A-Z]+$/);

		expect(rule('ABC')).toBe(true);
```

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
> +		expect(validator('abc')).toBe('The value must match the pattern.');
```suggestion
		const rule = matchPattern(/^[A-Z]+$/, {
			default: 'test'
		});

		expect(rule('abc')).toBe('test');
```

2023-06-07 16:17 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
Il manque un test si la valeur n'est pas valide sans messages d'erreur personnalisés

2023-06-08 07:55 UTC, DavidFyon commented on packages/docs/src/data/drawerItems.ts
j'ai juste mis la liste par ordre alphabétique, je peux la rechanger si besoin

2023-06-08 14:36 UTC, deraw commented on packages/docs/src/data/api/rules/match-pattern.ts
> +	},
```suggestion
				name: 'pattern',
				type: 'RegExp',
				description: 'L’expression régulière permettant de valider la valeur.',
			},
			...ruleMessages(`{
	default: 'Le format saisi ne correspond pas au format attendu.',
}`)
		]
	}
```

2023-06-08 14:42 UTC, deraw commented on packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
> +	});
```suggestion
	});

	it('should return an error if the value does not match the pattern', () => {
		const rule = matchPattern(/^[A-Z]+$/);

		expect(rule('ABC')).toBe('string');
	});
```

2023-06-08 14:42 UTC, deraw approved these changes

2023-06-08 14:43 UTC, deraw commented on packages/docs/src/data/drawerItems.ts
> +					},
```suggestion
					}
```

2023-06-08 15:05 UTC, merged