vue-dot : add PeriodField component
assurance-maladie-digital/design-system pull request #2923
Opened 2023-06-21 12:32 UTC by DavidFyon

## Description

Extraire le champ de formulaire PeriodField contenu dans FormField dans un nouveau composant du même nom, en utilisant ce nouveau composant dans period.vue dans le FormField (sans modifier l'utilisation).

La modification que l'on avait évoquée (utiliser la prop range du VDatePicker de Vuetify) n'est pas à faire car il faudrait modifier le composant DatePicker. Elle pourra être faite en v3 lors de la réécriture des composants.

## Playground

<details>

```vue
<template>
	<PageContainer>
		<PeriodField v-model="periodValue" />
		{{ periodValue }}
	</PageContainer>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {
		periodValue = {
			start: '2020-01-01',
			end: '2020-01-31'
		};
	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Refactoring
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-06-27 13:57 UTC, deraw requested changes

2023-06-27 13:57 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/AppHeader.vue
> +				v-for="(item, index) in navigationItems"HeaderBar
```suggestion
				v-for="(item, index) in navigationItems"
```

2023-06-27 13:57 UTC, deraw commented on packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
> +
```suggestion
```

2023-06-27 13:57 UTC, deraw commented on packages/vue-dot/src/patterns/index.ts
Il faut aussi ajouter le composant dans le fichier `vueDotLoader` du Starter Kit

2023-06-27 13:57 UTC, deraw commented on packages/form-builder/src/components/FormField/mixins/fieldMap.ts
> +import PeriodField from '../fields/Period.vue';
Il faudrait trouver un autre nom pour ce composant, il faut éviter les noms avec un seul mot

2023-06-27 13:57 UTC, deraw commented on packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
Les labels "Début" et "Fin" du champ période ont été remplacés par "Date", ça ne devrait pas 🤔

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/examples/period-field/outlined.vue
Pas besoin de cet exemple vu qu'il y a l'onglet dans la section utilisation

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/drawerItems.ts
Il faut aussi l'ajouter dans la page vue d'ensemble non ?

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/api/period-field.ts
> +				description: 'Si défini, le champ sera affiché avec un contour.',
```suggestion
				description: 'Affiche les `VTextField` en mode `outlined`.',
```

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/api/period-field.ts
> +				description: 'Si défini, le champ sera désactivé.',
```suggestion
				description: 'Désactive le champ.',
```

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/api/period-field.ts
> +				default: 'false'
```suggestion
				default: false
```

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/api/period-field.ts
> +			},
```suggestion
				default: false
			}
```

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/data/api/period-field.ts
> +		],
```suggestion
		]
```

2023-06-27 13:57 UTC, deraw commented on packages/docs/src/content/composants/formulaires/period-field.md
> +Le champ `PeriodField` est composé de deux [`DatePicker`](https://vuetifyjs.com/en/components/date-pickers/) et applique une validation sur la longueur du champ.
Tu as mis le lien vers la v3 et c'est plutôt le lien de notre DatePicker qu'il faut mettre

2023-07-03 08:28 UTC, christopheGaon commented on packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts
> +						label: 'V@otre date de naissance'
```suggestion
						label: 'Votre date de naissance'
```

2023-07-03 08:31 UTC, christopheGaon approved these changes

2023-07-27 23:24 UTC, deraw approved these changes

2023-07-27 23:33 UTC, merged