Vue-dot : HeaderBar Sticky improve
assurance-maladie-digital/design-system pull request #3037
Opened 2023-09-05 14:12 UTC by DavidFyon

## Description

Masquer la navigation au scroll par défaut en mode sticky + ajouter une option pour toujours l'afficher

## Playground

<details>

```vue
<template>
	<PageContainer>
		<HeaderBar
			:navigation-items="navigationItems"
			sticky
			:show-sticky-nav-bar="false"
		/>
		<VSheet style="height: 2000px">
			Content
		</VSheet>
	</PageContainer>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { NavigationItem } from '@cnamts/vue-dot/src/patterns/HeaderBar/types';

	@Component
	export default class HeaderBarNavigationBar extends Vue {
		navigationItems: NavigationItem[] = [
			{
				label: 'Accueil'
			},
			{
				label: 'Mes projets'
			},
			{
				label: 'Mes outils'
			}
		];
	}
</script>
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-09-05 14:46 UTC, deraw commented on packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
> +			<template v-if="showNavigationBar && !scrolled || showNavigationBar && (scrolled && showStickyNavBar)">
Est-ce que tu peux faire un getter vu que la condition est utilisée plusieurs fois stp ?

2023-09-05 15:37 UTC, deraw requested changes

2023-09-05 15:37 UTC, deraw commented on packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
> +			<template v-if="showNavigationBar && !scrolled || showNavigationBar && (scrolled && showStickyNavBar)">
Et il faut ajouter une transition, l'effet est un peu trop violent actuellement

2023-09-05 16:18 UTC, DavidFyon commented on packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
> +			this.prevScrollPosition = scrollPosition;
c'est pour afficher la navbar au scroll up en mode sticky, ça fonctionne bien sur le Playground mais dans la doc ça fait des chocapics :

Playground :
![2023-09-05 18 16 54](https://github.com/assurance-maladie-digital/design-system/assets/1822420/34882422-b095-492c-9d20-422d8d0b05e1)

Doc :
![2023-09-05 18 17 56](https://github.com/assurance-maladie-digital/design-system/assets/1822420/17a22917-8e45-4aca-acc9-4cc57f4e65f9)

J'enlève ça ?

2023-09-08 15:33 UTC, deraw approved these changes

2023-09-08 15:33 UTC, merged