DialogBox v3
assurance-maladie-digital/design-system pull request #3153
Opened 2023-10-06 13:43 UTC by DavidFyon

Add DialogBox component

```vue
<template>
	<div>
		<VBtn
			color="primary"
			@click="dialog = true"
		>
			Afficher le composant
		</VBtn>

		<DialogBox
			v-model="dialog"
			:width="dialogWidth"
			title="Enregistrement"
			@cancel="dialog = false"
			@confirm="dialog = false"
		>
			<p>Souhaitez-vous procéder à l’enregistrement ?</p>
		</DialogBox>
	</div>
</template>

<script lang="ts">
import DialogBox from "@/elements/DialogBox";
import { defineComponent } from "vue";

import { tokens } from '@cnamts/design-tokens';

export default defineComponent({
	components: {
		DialogBox,
	},
	data() {
		return {
			dialog: false,
			dialogWidth: tokens.dialogWidth.dialogSmall
		};
	},
});
</script>
```

2023-11-06 13:10 UTC, DavidFyon commented
Améliorer le test

2024-01-25 10:31 UTC, VachetVirginie approved these changes

2024-02-05 10:01 UTC, 4dr1en approved these changes

2024-02-06 14:36 UTC, deraw requested changes
Le comportement de la navigation au clavier n'est pas bonne, on peut naviguer en dehors de la modale avant que le focus tombe dedans

2024-03-05 13:35 UTC, deraw approved these changes

2024-03-05 13:36 UTC, merged