add component + tests
assurance-maladie-digital/design-system pull request #3159
Opened 2023-10-09 09:23 UTC by DavidFyon

Add DownloadBtn component

```vue
<template>
	<FileList :files="fileList" />
	<br /><br />
	<FileList :files="fileList2" />
</template>

<script lang="ts">
import FileList from "../src/elements/FileList";
import { defineComponent } from "vue";

import { FileItem } from "../src/elements/FileList/types";

export default defineComponent({
	components: {
		FileList,
	},
	data() {
		return {
			fileList: [
				{
					title: "RIB",
					state: "initial",
				},
				{
					title: "Carte d’identité recto / verso",
					state: "initial",
				},
				{
					title: "Passport",
					state: "initial",
				},
			] as FileItem[],

			fileList2: [
				{
					title: "RIB",
					name: "rib.pdf",
					state: "success",
				},
				{
					title: "Carte d’identité recto / verso",
					name: "carte-identite.jpg",
					state: "success",
				},
				{
					title: "Passport",
					name: "passport.jpg",
					state: "error",
				},
			] as FileItem[],
		};
	},
});
</script>
```

2023-10-09 09:25 UTC, DavidFyon commented
Tests à revoir

2023-11-06 13:31 UTC, DavidFyon commented
Améliorer les tests

2024-01-25 13:17 UTC, VachetVirginie requested changes

2024-01-25 13:17 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/FileList/FileList.vue
> +				<VListItemTitle
Pour eviter la dupication de code on pourrait faire: <template v-for="item in [file.title, file.optional ? optionalFileText : null, file.name]">
  <VListItemTitle
    v-if="item === file.title"
    :key="'title'"
    v-bind="options.listItemTitle"
    :class="[
      options.listItemTitle.class,
      getItemColor(file.state),
    ]"
  >
    {{ item }}
  </VListItemTitle>

  <VListItemSubtitle
    v-if="item && item !== file.title"
    :key="'subtitle-' + item"
    v-bind="options.listItemSubtitle"
  >
    {{ item }}
  </VListItemSubtitle>
</template>

2024-01-25 13:17 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/FileList/FileList.vue
> +				<VListItemSubtitle
il faut ajouter un espace sur la classe .v-list-item-subtitle car le bas du texte est rogne: 
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/c8dc9ac4-0f71-482f-8a8d-290cfe91fd4c)

2024-01-29 14:03 UTC, VachetVirginie requested changes

2024-01-29 14:03 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/FileList/FileList.vue
> +	line-height: 1.;
Un chiffre a saute

2024-01-30 09:43 UTC, VachetVirginie approved these changes

2024-02-05 10:20 UTC, 4dr1en requested changes
Les tests emmettent des warnings parce que il y a des erreures sur la façon dont la props `file` est passé au composant.

2024-04-09 14:36 UTC, VachetVirginie approved these changes

2024-04-10 08:33 UTC, merged