ExternalLink v3
assurance-maladie-digital/design-system pull request #3160
Opened 2023-10-09 09:47 UTC by DavidFyon

Add ExternaLink component

```vue
<template>
	<PageContainer>
		<VCard min-height="274px" class="mx-auto overflow-hidden">
			<ExternalLinks :items="links" position="top left" />
			<ExternalLinks :items="links" nudge-top="80px" position="top right" />
		</VCard>
	</PageContainer>
</template>

<script lang="ts">
import ExternalLinks from "../src/elements/ExternalLinks";
import PageContainer from "../src/elements/PageContainer";
import { defineComponent } from "vue";

import { tokens } from '@cnamts/design-tokens';

import type { ExternalLink } from '../src/elements/ExternalLinks/types';

export default defineComponent({
	components: {
		ExternalLinks,
		PageContainer
	},
	data() {
		return {
			appBarColor: tokens.colors.amBlue.lighten97,
			links: [
				{
					href: 'https://ameli.fr/',
					text: 'Ameli'
				},
				{
					href: 'https://espacepro.ameli.fr/',
					text: 'Ameli Pro'
				}
			] as ExternalLink[]
		};
	},
});
</script>
```

2023-10-26 11:53 UTC, DavidFyon commented
Le text des Btn sera en minuscule avec les variables SASS https://github.com/assurance-maladie-digital/design-system/pull/3154

2023-10-30 09:28 UTC, DavidFyon commented
Il faudra peux être revoir l'import de la Source Sans 3, la weight 600 des Btn n'a pas l'air de correspondre

![Capture d’écran 2023-10-30 à 10 26 52](https://github.com/assurance-maladie-digital/design-system/assets/1822420/773c326f-3533-4731-b0d9-1b4bf980780b)
![Capture d’écran 2023-10-30 à 10 26 57](https://github.com/assurance-maladie-digital/design-system/assets/1822420/730142af-1cbd-478f-a8bd-fa7d94306149)

2024-01-24 16:36 UTC, VachetVirginie requested changes

2024-01-24 16:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/ExternalLinks/ExternalLinks.vue
> +				translateValue = this.right
il faut tenir compte de la taille du texte sinon ca risque de poser probleme

2024-01-25 09:58 UTC, DavidFyon commented on packages/synapse-bridge/src/elements/ExternalLinks/ExternalLinks.vue
> +				translateValue = this.right
on peux modifier la largeur dans les options (config.ts)

2024-01-25 10:15 UTC, DavidFyon commented on packages/synapse-bridge/src/elements/ExternalLinks/ExternalLinks.vue
> +				<VIcon v-bind="options.btnIcon">
yup

2024-01-30 09:44 UTC, VachetVirginie approved these changes

2024-02-05 10:29 UTC, 4dr1en approved these changes

2024-02-06 16:57 UTC, deraw approved these changes

2024-02-06 16:58 UTC, deraw commented
Le code me semble bien, par contre j'ai détecté un soucis avec le menu. Si le bouton est cliqué avant la fin de l'animation, celle-ci s'arrête et le menu reste où il est, avec du texte caché :

![Capture d'écran 2024-02-06 160751](https://github.com/assurance-maladie-digital/design-system/assets/10298932/c73f0739-7d73-4b40-958c-b376ed1fb65c)

2024-04-16 10:14 UTC, merged