WIP - FileUpload + FilePreview v3
assurance-maladie-digital/design-system pull request #3162
Opened 2023-10-09 14:05 UTC by DavidFyon

FileUpload + FilePreview

```vue
<template>
	<div>
		<FileUpload v-model="file" :class="{ 'mb-8': file !== null }" />
		<FilePreview :file="file" />

		<FilePreview :file="file2" :options="options" />
	</div>
</template>

<script lang="ts">
import FileUpload from "../src/patterns/FileUpload";
import FilePreview from "../src/elements/FilePreview";

import { defineComponent } from "vue";

export default defineComponent({
	components: {
		FileUpload,
		FilePreview,
	},
	data() {
		return {
			file: null,
			file2: null,

			options: {
				image: {
					alt: "Photo de paysage montagneux du site Picsum.",
				},
			},
		};
	},
	mounted() {
		fetch("https://picsum.photos/seed/picsum/750/350")
			.then((res) => res.blob())
			.then((blob) => (this.file2 = blob));
	},
});
</script>
```

2023-10-09 14:06 UTC, DavidFyon commented
FilePreview.vue : `this.fileURL` semble vide
Revoir les tests

2024-01-29 09:51 UTC, VachetVirginie reviewed
Où se fait la verification sur la taille des documents?

2024-01-29 09:51 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/FilePreview/FilePreview.vue
> +			v-if="isPdf"
Meme s'il n'y a pas de convention de nommage stricte pour les variables booléennes nous pourrions adopter cette maniere de les declarer de partout, ca nous permettra de rendre plus lisible le code ;) (dans d'autres fichiers les booleans ne commencent pas par is)

2024-01-29 09:51 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/FilePreview/FilePreview.vue
> +				{{ locales.previewTypeNotAvailable }}
il ne manque pas le Slot pour remplacer le message par défaut lorsqu’un type de fichier n’est pas supporté?

2024-01-29 14:45 UTC, DavidFyon commented on packages/synapse-bridge/src/elements/FilePreview/FilePreview.vue
> +				{{ locales.previewTypeNotAvailable }}
Tu peux le remplacer comme ça (je l'ai rajouté dans le playground) :

```vue
<FilePreview :file="file3">
	<template #default>
		Ce format ne convient pas.
	</template>
</FilePreview>
```

2024-01-30 13:47 UTC, DavidFyon commented
> Où se fait la verification sur la taille des documents?

je ne crois pas qu'on fasse une vérification @deraw  ?

2024-01-31 08:34 UTC, VachetVirginie approved these changes

2024-02-05 12:29 UTC, 4dr1en approved these changes

2024-04-17 17:37 UTC, 4dr1en requested changes
- [ ] Le champ fileUpload ne fourni aucuns indicatif visuel quand il est disable.
- [ ] La console affiche des erreurs si l'on drag and drop un seul fichier dans un champ upload avec la props multiple (Uncaught (in promise) TypeError: URL.createObjectURL: Argument 1 is not valid for any of the 1-argument overloads.)

2024-04-19 09:02 UTC, DavidFyon commented
> * [x]  Le champ fileUpload ne fourni aucuns indicatif visuel quand il est disable.
> * [x]  La console affiche des erreurs si l'on drag and drop un seul fichier dans un champ upload avec la props multiple (Uncaught (in promise) TypeError: URL.createObjectURL: Argument 1 is not valid for any of the 1-argument overloads.)

Playground modifié (l'erreur TS était du au fait qu'on faisait un rendu d'1 fichier sur un upload multiple)

2024-04-19 14:26 UTC, 4dr1en requested changes
le drag and drop fonctionne toujours sur un champ disabled

2024-04-19 15:39 UTC, DavidFyon commented
> le drag and drop fonctionne toujours sur un champ disabled

Faudra que tu me montres car moi ça n'upload pas si c'est disabled

2024-04-19 17:22 UTC, 4dr1en commented
> > le drag and drop fonctionne toujours sur un champ disabled
> 
> Faudra que tu me montres car moi ça n'upload pas si c'est disabled

![Peek 2024-04-19 19-19](https://github.com/assurance-maladie-digital/design-system/assets/65124433/7c027bd8-a0b9-4644-ad98-845e715d9f38)

2024-04-29 11:52 UTC, 4dr1en approved these changes

2024-05-06 14:10 UTC, merged