AlertWrapper v3
assurance-maladie-digital/design-system pull request #3167
Opened 2023-10-10 15:32 UTC by DavidFyon

Add component + test

```vue
<template>
	<PageContainer>
		<AlertWrapper type="info">
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="info" outlined>
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="success">
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="success" outlined>
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="error" v-model="alert" dismissible>
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="error" outlined>
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper type="warning">
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<br />

		<AlertWrapper
			v-model="alert"
			dismissible
			outlined
			type="warning"
			class="mb-0"
		>
			Il semble qu’une date de naissance erronée a été saisie,
			renseignez-vous auprès du centre qui vous a vacciné.
		</AlertWrapper>

		<VBtn v-if="!alert" color="primary" @click="alert = true">
			Réinitialiser
		</VBtn>
	</PageContainer>
</template>

<script lang="ts">
import AlertWrapper from "../src/patterns/AlertWrapper/AlertWrapper.vue";
import PageContainer from "../src/elements/PageContainer";

import { defineComponent } from "vue";

export default defineComponent({
	components: {
		AlertWrapper,
		PageContainer,
	},
	data() {
		return {
			alert: true,
		};
	},
});
</script>
```

2023-10-10 15:54 UTC, DavidFyon commented
la @mixin redesign ne semble pas prise en compte

2024-02-05 12:40 UTC, 4dr1en requested changes

2024-02-05 12:40 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/AlertWrapper/AlertWrapper.vue
> +			type: String,
```suggestion
			type: String as PropType<AlertTypeEnum>,
```

2024-02-12 08:27 UTC, 4dr1en approved these changes

2024-03-10 09:54 UTC, merged