DataListGroup v3
assurance-maladie-digital/design-system pull request #3170
Opened 2023-10-11 09:23 UTC by DavidFyon

Add DataListGroup

```vue
<template>
	<PageContainer>
		<DataListGroup
			:items="items"
			:icons="icons"
			@click:list-item="updateBirthdate"
		/>
		<br /><br />
		<DataListGroup
			:items="items"
			item-width="300px"
		/>
		<br /><br />
		<DataListGroup
			:items="items"
			loading
		/>
	</PageContainer>
</template>

<script lang="ts">
import DataListGroup from "../src/patterns/DataListGroup/DataListGroup.vue";
import PageContainer from "@/elements/PageContainer/PageContainer.vue";

import { defineComponent } from "vue";

import { DataListIcons } from '../src/elements/DataList/types';
import { DataListActionEvent, DataListGroupItems } from '../src/patterns/DataListGroup/types';

import {
	mdiCalendar,
	mdiAccount,
	mdiDoctor,
	mdiCardAccountDetails,
	mdiPencil
} from '@mdi/js';

export default defineComponent({
	components: {
		PageContainer,
		DataListGroup,
	},
	data() {
		return {
			items: [
				{
					title: 'Informations patient',
					items: [
						{
							key: 'Nom',
							value: 'Dupont',
							icon: 'accountIcon',
							chip: true
						},
						{
							key: 'Prénom',
							value: 'Paul',
							icon: 'accountIcon'
						},
						{
							key: 'Date de naissance',
							value: '24/09/1970',
							icon: 'calendarIcon',
							action: 'Modifier'
						}
					]
				},
				{
					title: 'Médecin traitant',
					items: [
						{
							key: 'Nom du praticien',
							value: 'Gérard Leblanc',
							icon: 'doctorIcon'
						},

						{
							key: 'N° RPPS',
							value: 'XXXXX',
							icon: 'cardAccountIcon'
						}
					]
				},
				{
					title: 'Autres informations',
					items: [
						{
							key: 'Dernière modification',
							value: '04/06/2020',
							icon: 'editIcon'
						}
					]
				}
			] as DataListGroupItems,

			icons: {
				calendarIcon: mdiCalendar,
				accountIcon: mdiAccount,
				doctorIcon: mdiDoctor,
				cardAccountIcon: mdiCardAccountDetails,
				editIcon: mdiPencil
			} as DataListIcons
		};
	},
	methods: {
		updateBirthdate({ dataListIndex, itemIndex }: DataListActionEvent): void {
			this.items[dataListIndex].items[itemIndex].value = '01/01/1970';
		}
	}
});
</script>
```

2023-10-11 09:24 UTC, DavidFyon commented
Besoin de merger `DataList` pour utiliser le composant

2024-01-30 16:12 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/DataListGroup/DataListGroup.vue
> +		loading: {
isLoading

2024-01-30 16:12 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/DataListGroup/DataListGroup.vue
> +		renderHtmlValue: {
isRenderHtmlValue

2024-01-30 16:12 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/DataListGroup/DataListGroup.vue
> +			:key="'vd-data-list-' + index"
:key="`vd-data-list-${index}`"

2024-01-30 16:12 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/DataListGroup/types.d.ts
> +	headingLoading?: boolean;
isHeadingLoading

2024-02-01 15:15 UTC, VachetVirginie approved these changes

2024-02-05 12:47 UTC, 4dr1en requested changes

2024-02-05 12:47 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/DataListGroup/DataListGroup.vue
> +import DataList from "../../elements/DataList/DataList.vue";
```suggestion
import DataList from "@/elements/DataList/DataList.vue";
```

2024-02-05 12:47 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/DataListGroup/DataListGroup.vue
> +import type { DataListIcons } from "../../elements/DataList/types";
```suggestion
import type { DataListIcons } from "@/elements/DataList/types";
```

2024-02-12 08:23 UTC, 4dr1en approved these changes

2024-02-16 10:57 UTC, merged