LanBtn v3
assurance-maladie-digital/design-system pull request #3177
Opened 2023-10-12 07:25 UTC by DavidFyon

LanBtn + test

```vue
<template>
	<PageContainer>
		<LangBtn />
		<br /><br />
		<LangBtn
			value="en"
			:available-languages="[
				'fr',
				'en',
				'de',
				'zh'
			]"
		/>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import LangBtn from '@/patterns/LangBtn/LangBtn.vue';
import PageContainer from '@/elements/PageContainer/PageContainer.vue';

export default defineComponent({
	components: {
		LangBtn,
		PageContainer,
	},
});
</script>
```

2024-01-30 16:04 UTC, VachetVirginie approved these changes

2024-02-05 12:54 UTC, 4dr1en requested changes

2024-02-05 12:54 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/LangBtn/LangBtn.vue
> +import { customizable } from "../../mixins/customizable";
```suggestion
import { customizable } from "@/mixins/customizable";
```

2024-02-05 12:54 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/LangBtn/tests/LangBtn.spec.ts
> +		console.log(wrapper.emitted());
```suggestion
```

2024-02-09 12:19 UTC, DavidFyon commented on packages/synapse-bridge/src/patterns/LangBtn/LangBtn.vue
> +/// <reference path="./languages.d.ts" />
A garder @4dr1en  ?

2024-02-09 12:19 UTC, DavidFyon reviewed
@4dr1en il faudra rajouter les modifs faites en V2

2024-03-04 16:52 UTC, 4dr1en commented
> @4dr1en il faudra rajouter les modifs faites en V2

done

2024-03-04 16:54 UTC, 4dr1en approved these changes

2024-03-04 16:54 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/LangBtn/LangBtn.vue
> +/// <reference path="./languages.d.ts" />
yes c'est pour intégrer le fichier de déclaration des types du module language

2024-03-19 09:55 UTC, merged