NirField v3
assurance-maladie-digital/design-system pull request #3181
Opened 2023-10-12 12:55 UTC by DavidFyon

NirField

```vue
<template>
	<PageContainer>
		<NirField />
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import NirField from "@/patterns/NirField/NirField.vue";
import PageContainer from "@/elements/PageContainer/PageContainer.vue";

export default defineComponent({
	components: {
		NirField,
		PageContainer,
	},
	data() {
		return {
			//
		};
	},
});
</script>
```

2023-10-12 12:57 UTC, DavidFyon commented
Des soucis sur l'input des champs

2023-10-24 13:22 UTC, DavidFyon commented
Validation des champs à faire fonctionner

2023-11-02 15:25 UTC, DavidFyon commented
Warning à corriger + tests à améliorer

2024-01-31 08:40 UTC, VachetVirginie approved these changes

2024-01-31 09:17 UTC, DavidFyon commented
Ajouter les derniers changements v2

2024-02-23 13:05 UTC, VachetVirginie approved these changes

2024-03-22 08:37 UTC, 4dr1en requested changes
- [ ] Lors de la frappe, le message d'erreur apparait et disparait un caractère sur deux
 
- [ ] Le hint de la clé ne devrait pas disparaitre

 - [x] Lors de la perte de focus, le message d'erreure devrait etre visible,

 - [x] Le champs de text 'number' et 'key' ont un text de couleur différent.

 - [x] l'écartement entre le champs de text et le tooltip devrait etre identique entre le mode simple et double.

2024-03-22 08:37 UTC, 4dr1en commented on packages/synapse-bridge/src/elements/BackToTopBtn/BackToTopBtn.vue
> +
Pourquoi y a t'il des changements sur le composant BackToTopBtn ?

2024-03-22 09:00 UTC, DavidFyon commented
![Capture d’écran 2024-03-22 à 09 58 26](https://github.com/assurance-maladie-digital/design-system/assets/1822420/cd575b22-4f8f-4b2c-b058-cf557d266f4d)

 Le hint de la clé ne devrait pas disparaitre

2024-03-22 09:27 UTC, VachetVirginie commented on packages/synapse-bridge/src/elements/BackToTopBtn/BackToTopBtn.vue
> +
Vu avec David

2024-03-22 14:31 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/NirField/NirField.vue
> -		},
le blur le gere

2024-03-28 14:58 UTC, 4dr1en approved these changes

2024-03-29 13:10 UTC, merged