add components + tests
assurance-maladie-digital/design-system pull request #3183
Opened 2023-10-13 07:24 UTC by DavidFyon

PasswordField

```vue
<template>
	<PageContainer>
		<PasswordField required />
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import PasswordField from "@/patterns/PasswordField/PasswordField.vue";

export default defineComponent({
	components: {
		PageContainer,
		PasswordField,
	},
});
</script>
```

2024-01-29 15:38 UTC, VachetVirginie requested changes

2024-01-29 15:38 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/PasswordField/PasswordField.vue
> +		@update:model-value="emitChangeEvent"
@change="emitChangeEvent" car sinon cela provoque un bug: a chaque fois que l'on clique sur l'oeil pour hide ou pas le mot de passe celui ci est ecrase

2024-01-31 08:42 UTC, VachetVirginie approved these changes

2024-02-05 13:06 UTC, 4dr1en requested changes
L'utilisation de `v-model` sur ce composant ne fonctionne plus. Il faudrait repasser sur un event `update:modelValue` plutôt que `change`.
https://v3-migration.vuejs.org/breaking-changes/v-model.html

2024-04-17 07:21 UTC, VachetVirginie approved these changes

2024-04-17 11:31 UTC, 4dr1en approved these changes

2024-04-17 11:53 UTC, merged