WIP - PhoneField v3
assurance-maladie-digital/design-system pull request #3185
Opened 2023-10-13 14:15 UTC by DavidFyon

PhoneField

```vue
<template>
	<PageContainer>
		<PhoneField required @change="handleInputChange" />
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import PhoneField from "@/patterns/PhoneField/PhoneField.vue";
import PageContainer from "@/elements/PageContainer/PageContainer.vue";

export default defineComponent({
	components: {
		PhoneField,
		PageContainer,
	},
	methods: {
		handleInputChange(value: string) {
			console.log(value);
		}
	}
});
</script>
```

2023-10-13 14:16 UTC, DavidFyon commented
Todo : récupérer la valeur du field

2023-11-06 10:05 UTC, DavidFyon commented
Améliorer les tests

2024-01-29 10:27 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +		required: {
isRequired?

2024-01-29 10:27 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +		outlined: {
isOutlined?

2024-01-29 10:27 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +		},
On peut simplifier: rules(): ValidationRule[] {
  return this.required ? [required, exactLength(PHONE_LENGTH, true)] : [exactLength(PHONE_LENGTH, true)];
},

2024-01-29 10:27 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +		},
on peut simplifier:
formatPhone(value: string): string {
  return value.replace(/(.{2})/g, "$1 ").trim();
}

2024-01-31 08:39 UTC, VachetVirginie approved these changes

2024-02-05 13:24 UTC, 4dr1en requested changes

2024-02-05 13:24 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +		@change="emitChangeEvent"
L'api de ce composant vuetify a changé avec la v3 https://dev.vuetifyjs.com/en/api/v-text-field/#events
il faudrait utiliser `update:modelValue`.

2024-02-05 13:24 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +import { required } from "../../rules/required";
```suggestion
import { required } from "@/rules/required";
```

2024-02-05 13:24 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
> +import { exactLength } from "../../rules/exactLength";
```suggestion
import { exactLength } from "@/rules/exactLength";
```

2024-02-12 08:18 UTC, 4dr1en approved these changes

2024-03-18 10:59 UTC, merged