TableToolbar v3
assurance-maladie-digital/design-system pull request #3198
Opened 2023-10-17 09:27 UTC by DavidFyon

TableToolbar

```vue
<template>
	<PageContainer>
		<VDataTable
			:headers="headers"
			:items="items"
			:search="search"
			hide-default-footer
		>
			<template #top>
				<TableToolbar
					v-model="search"
					:nb-total="items.length"
					show-add-btn
					@search="search = $event.target.value"
				/>
			</template>
		</VDataTable>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { VDataTable } from "vuetify/labs/VDataTable";

import TableToolbar from "@/patterns/TableToolbar/TableToolbar.vue";
import PageContainer from "@/elements/PageContainer/PageContainer.vue";

export default defineComponent({
	components: {
		TableToolbar,
		VDataTable,
		PageContainer,
	},
	data() {
		return {
			search: null as string | null,
			headers: [
				{
					title: "Nom",
					key: "lastname",
				},
				{
					title: "Prénom",
					key: "firstname",
				},
				{
					title: "Email",
					key: "email",
				},
			],

			items: [
				{
					firstname: "Virginie",
					lastname: "Beauchesne",
					email: "virginie.beauchesne@example.com",
				},
				{
					firstname: "Étienne",
					lastname: "Salois",
					email: "etienne.salois@example.com",
				},
			],
		};
	},
});
</script>
```

2023-10-17 09:29 UTC, DavidFyon commented
Le test ne passe pas alors que cela fonctionne sur PageContainer par exemple

![Capture d’écran 2023-10-17 à 11 28 25](https://github.com/assurance-maladie-digital/design-system/assets/1822420/316c2b67-cc7f-417a-a861-e2caa90c1b81)

2023-11-13 09:42 UTC, DavidFyon commented
Tests à améliorer

2024-01-10 13:06 UTC, DavidFyon commented
improve test coverage

2024-02-05 13:58 UTC, 4dr1en requested changes
Certains tests génèrent des warnings

2024-02-05 13:58 UTC, 4dr1en commented on packages/synapse-bridge/src/patterns/TableToolbar/TableToolbar.vue
> +	emits: ["search"],
```suggestion
	emits: ["search", "click"],
```

2024-02-14 15:53 UTC, 4dr1en requested changes
Il faudrait emmètre un event `update:search` pour utiliser search de façon réactive comme avec la v2 :

```typescript 
<template>
	<VDataTable
		:headers="headers"
		:items="items"
		:search="search"
		hide-default-footer
	>
		<template #top>
			<TableToolbar
				v-model="search"
				:nb-total="items.length"
				show-add-btn
			/>
		</template>
	</VDataTable>
</template>
```

https://vuejs.org/guide/components/v-model.html#v-model-arguments

2024-03-07 15:37 UTC, 4dr1en commented
> Il faudrait emmètre un event `update:search` pour utiliser search de façon réactive comme avec la v2 :
> 
> ```ts
> <template>
> 	<VDataTable
> 		:headers="headers"
> 		:items="items"
> 		:search="search"
> 		hide-default-footer
> 	>
> 		<template #top>
> 			<TableToolbar
> 				v-model="search"
> 				:nb-total="items.length"
> 				show-add-btn
> 			/>
> 		</template>
> 	</VDataTable>
> </template>
> ```
> 
> https://vuejs.org/guide/components/v-model.html#v-model-arguments

corrigé dans le dernier commit 
@DavidFyon

2024-03-20 13:48 UTC, VachetVirginie approved these changes

2024-03-20 13:48 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/TableToolbar/TableToolbar.vue
> +		},
showRowsNumber(): boolean {
    return this.nbTotal;
  }, 
0, null, undefined, et '' sont tous falsy, donc si this.nbTotal est l'une de ces valeurs, il sera converti en false.

2024-03-20 13:48 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/TableToolbar/TableToolbar.vue
> +		},
computedNbRows(): string {
    return this.nbFiltered !== undefined ? `${this.nbFiltered}/${this.nbTotal}` : `${this.nbTotal}`;
  },

2024-03-20 13:48 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/TableToolbar/TableToolbar.vue
> +		},
computedRowsText(): string {
    return locales.rowText(this.rowText, this.nbTotal > 1);
  },

2024-03-20 13:58 UTC, VachetVirginie approved these changes

2024-03-20 15:22 UTC, DavidFyon commented on packages/synapse-bridge/src/patterns/TableToolbar/TableToolbar.vue
> +		},
il ne peux pas être null, undefined ou un string (type Number)
Si on supprime le typage en Boolean cela ajouter une erreur ts

2024-03-21 12:19 UTC, VachetVirginie commented
> soucis avec `:nb-filtered` à résoudre

Done ;)

2024-03-22 09:21 UTC, 4dr1en requested changes
- [x] Quand la props 'loading' est défini sur true, le style n'est pas le même que sur la v2

- [x] les éléments devraient être aligné verticalement sur la barre.

- [x]  Il manque une marge sur la gauche.

2024-03-29 11:03 UTC, 4dr1en approved these changes

2024-04-05 12:46 UTC, VachetVirginie approved these changes

2024-04-05 13:10 UTC, merged