SearchListField v3
assurance-maladie-digital/design-system pull request #3204
Opened 2023-10-18 12:15 UTC by DavidFyon

SearchListField

```vue
<template>
	<PageContainer>
		<SearchListField
			v-model="value"
			:items="items"
		/>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import SearchListField from "@/patterns/SearchListField/SearchListField.vue";

import { SearchListItem } from '@/patterns/SearchListField/types';

export default defineComponent({
	components: {
		PageContainer,
		SearchListField
	},
	data() {
		return {
			value: [] as string[],

			items: [
				{
					label: 'Chirurgien-dentiste',
					value: 'chirurgien-dentiste'
				},
				{
					label: 'Infirmier',
					value: 'infirmier'
				},
				{
					label: 'Orthophoniste',
					value: 'orthophoniste'
				},
				{
					label: 'Orthoptiste',
					value: 'orthoptiste'
				},
				{
					label: 'Pédicure-podologue',
					value: 'pedicure-podologue'
				},
				{
					label: 'Pharmacien',
					value: 'pharmacien'
				}
			] as SearchListItem[]
		};
	},
});
</script>
```

2024-01-29 10:15 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/SearchListField/SearchListField.vue
> +		filteredItems(): SearchListItem[] {
on peut simplifier: filteredItems(): SearchListItem[] {
  if (this.search === null) {
    return this.items;
  }
  const searchLower = this.search.toLowerCase();
  return this.items.filter(item => item.label.toLowerCase().includes(searchLower));
},

2024-01-30 13:43 UTC, DavidFyon commented on packages/synapse-bridge/src/patterns/SearchListField/SearchListField.vue
> +		filteredItems(): SearchListItem[] {
ok tu peux faire un commit pour ça et relancer les tests

2024-01-31 08:30 UTC, VachetVirginie approved these changes

2024-01-31 08:32 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/SearchListField/SearchListField.vue
> +		filteredItems(): SearchListItem[] {
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/0fee048c-9fdb-493b-ae7f-4e30c264d6a1)

2024-04-10 08:42 UTC, 4dr1en requested changes
Les tests emmettent de nombreux warnings sur ma machine

2024-04-10 09:00 UTC, 4dr1en approved these changes

2024-04-10 09:00 UTC, merged