NotificationBar v3
assurance-maladie-digital/design-system pull request #3206
Opened 2023-10-18 15:35 UTC by DavidFyon

NotificationBar

**NB : supprimer les node_modules et faire un pnpm install pour faire marcher la PR**

```vue
<template>
	<PageContainer>
		<div class="d-flex flex-wrap align-center justify-center ma-n2">
			<NotificationBar v-show="showNotificationBar1">
				<template #action>
					<VBtn
						variant="outlined"
						color="white"
						@click="removeNotification1"
					>
						2ème action
					</VBtn>
				</template>
			</NotificationBar>

			<NotificationBar
				v-show="showNotificationBar2"
				type="error"
				bottom
			/>

			<VBtn
				color="primary"
				class="ma-2 mt-12"
				@click="createNotification1"
			>
				Envoyer une notification 1
			</VBtn>

			<VBtn
				color="primary"
				class="ma-2 mt-12"
				@click="createNotification2"
			>
				Envoyer une notification 2
			</VBtn>

			<VBtn
				color="primary"
				variant="outlined"
				class="ma-2 mt-12"
				@click="removeNotification"
			>
				Supprimer les notifications
			</VBtn>
		</div>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import NotificationBar from "@/patterns/NotificationBar/NotificationBar.vue";
import { mapActions, mapGetters } from "vuex";

export default defineComponent({
	components: {
		PageContainer,
		NotificationBar
	},
	computed: {
		...mapGetters('notification', {
			notification: 'notification',
		}),
		showNotificationBar1(): boolean {
			return this.notification?.ref === "1";
		},
		showNotificationBar2(): boolean {
			return this.notification?.ref === "2";
		}
	},
	methods: {
		...mapActions('notification', {
			dispatchNotification: 'addNotification',
			dispatchClearNotification: 'clearNotification',
		}),
		createNotification1(): void {
			this.dispatchNotification({
				ref: "1",
				type: 'info',
				message: 'Exemple de notification 1.',
			})
		},
		createNotification2(): void {
			this.dispatchNotification({
				ref: "2",
				type: 'warning',
				message: 'Exemple de notification 2.',
			})
		},
		removeNotification(): void {
			this.dispatchClearNotification();
		}
	}
});
</script>
```

2023-10-19 08:19 UTC, DavidFyon commented
J'accède bien au store mais je n'arrive pas à lancer les Actions

![Capture d’écran 2023-10-19 à 10 19 11](https://github.com/assurance-maladie-digital/design-system/assets/1822420/490ba772-c918-4339-9763-77e832283d23)

2024-02-14 15:13 UTC, DavidFyon commented
Améliorer le coverage

2024-03-08 14:56 UTC, VachetVirginie commented
@deraw Hello je ne comprends pas comment le store gere les ref

2024-03-08 16:10 UTC, 4dr1en requested changes
Il semble y avoir un problème avec le package-lock, les tests ne passent plus.

2024-03-08 19:36 UTC, VachetVirginie commented
> Il semble y avoir un problème avec le package-lock, les tests ne passent plus.

Ca refait la meme chose que l'autre fois je vois avec David lundi ;)

2024-03-09 23:21 UTC, deraw commented
> @deraw Hello je ne comprends pas comment le store gere les ref si tu as deux secondes pour m'expliquer comment cibler une notif via sa ref fais signe stp ;)

En fait c'est une fonctionnalité que j'ai ajouté surtout pour la documentation, dans le cas où on a plusieurs fois le composant sur la même page
Le store stocke juste la ref, c'est lors de l'utilisation qu'on vérifie que c'est la bonne notification à afficher :
```ts
get showNotificationBar(): boolean {
	return this.notification?.ref === EXAMPLE_REF;
}
```
(https://github.com/assurance-maladie-digital/design-system/blob/v2/packages/docs/src/data/examples/notification-bar/usage.vue)

2024-03-12 07:54 UTC, VachetVirginie commented on packages/synapse-bridge/src/modules/notification/tests/notify.spec.ts
> +	type: "success",
pareil pour la ref

2024-03-12 10:13 UTC, VachetVirginie approved these changes

2024-03-12 11:02 UTC, 4dr1en approved these changes

2024-03-12 11:15 UTC, merged