RangeField v3
assurance-maladie-digital/design-system pull request #3210
Opened 2023-10-19 11:36 UTC by DavidFyon

RangeField

```vue
<template>
	<PageContainer>
		<RangeField :max="100" />
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import RangeField from "@/patterns/RangeField/RangeField.vue";

export default defineComponent({
	components: {
		PageContainer,
		RangeField,
	},
});
</script>
```

2023-12-08 10:32 UTC, DavidFyon commented
Il reste 2 tests à faire passer (+ les warnings)

2024-01-24 14:17 UTC, VachetVirginie requested changes

2024-01-24 14:17 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/RangeField/RangeField.vue
> +				this.setRangeValue(RangeEnum.MIN, this.minValue);
Si la valeur minimale est superieur a la valeur max cela fonctionne quand meme.
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/3442d839-9e35-4719-a158-7835e36cb012)

2024-01-25 14:22 UTC, VachetVirginie approved these changes

2024-02-05 14:38 UTC, 4dr1en requested changes
Il faudrait utiliser `update:ModelValue`

2024-02-08 08:52 UTC, DavidFyon commented
> Il faudrait utiliser `update:ModelValue`. https://v3-migration.vuejs.org/breaking-changes/v-model.html

`update:ModelValue` n'a pas l'air d'être pris en compte par le composant Vuetify :
https://vuetifyjs.com/en/components/range-sliders/

2024-02-08 10:13 UTC, 4dr1en requested changes
Il faudrait utiliser `modelValue` à la place de `value` et `update:modelValue` à la place de `change` pour pouvoir utiliser le composant avec `v-model` comme c'est le cas dans la v2.

Voir le guide de migration de Vue : https://v3-migration.vuejs.org/breaking-changes/v-model.html

Voici le cas d'utilisation :
```
<template>
	<PageContainer>
		<RangeField v-model="rangeValue" :min="20" :max="100" />
		<p>Value: {{ rangeValue }}</p>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import RangeField from "@/patterns/RangeField/RangeField.vue";

export default defineComponent({
	components: {
		PageContainer,
		RangeField,
	},
	data() {
		return {
			rangeValue: [50, 80],
		};
	},
});
</script>
```

2024-02-09 11:51 UTC, 4dr1en approved these changes

2024-04-05 11:48 UTC, merged