FiltersInline v3
assurance-maladie-digital/design-system pull request #3227
Opened 2023-10-24 09:11 UTC by DavidFyon

FiltersInline

```vue
<template>
	<PageContainer>
		<FiltersInline v-model="filters">
			<template #name="{ attrs }">
				<VTextField
					v-bind="attrs"
					label="Nom"
					variant="outlined"
					hide-details
				/>
			</template>

			<template #folder="{ attrs }">
				<p class="text--secondary">
					Vous pouvez filtrer entre les dossiers de type
					<b>Arrêt de Travail (AT)</b> et
					<b>Maladie Professionnelle (MP)</b> ou <b>Autre</b>.
				</p>

				<VSelect
					v-bind="attrs"
					:items="folderTypes"
					label="Type de dossier"
					multiple
					variant="outlined"
					return-object
					hide-details
				/>
			</template>

			<template #period="{ attrs }">
				<PeriodField v-bind="attrs" outlined />
			</template>

			<template #profession="{ attrs }">
				<SearchListField
					v-bind="attrs"
					:items="professionList"
				/>
			</template>
		</FiltersInline>
	</PageContainer>
</template>

<script lang="ts">
import PageContainer from "@/elements/PageContainer/PageContainer.vue";
import FiltersInline from "@/patterns/FiltersInline/FiltersInline.vue";
import PeriodField from "@/patterns/PeriodField/PeriodField.vue";
import SearchListField from "@/patterns/SearchListField/SearchListField.vue";

import { defineComponent } from "vue";

export default defineComponent({
	components: {
		PageContainer,
		FiltersInline,
		PeriodField,
		SearchListField,
	},
	data() {
		return {
			filters: [
				{
					name: "name",
					title: "Identité",
				},
				{
					name: "folder",
					title: "Type de dossier",
				},
				{
					name: "period",
					title: "Période",
				},
				{
					name: "profession",
					title: "Profession",
				},
			],

			folderTypes: [
				{
					text: "AT",
					value: "at",
				},
				{
					text: "MP",
					value: "mp",
				},
				{
					text: "Autre",
					value: "other",
				},
			],

			professionList: [
				{
					label: "Chirurgien-dentiste",
					value: "chirurgien-dentiste",
				},
				{
					label: "Infirmier",
					value: "infirmier",
				},
				{
					label: "Orthophoniste",
					value: "orthophoniste",
				},
				{
					label: "Orthoptiste",
					value: "orthoptiste",
				},
				{
					label: "Pédicure-podologue",
					value: "pedicure-podologue",
				},
				{
					label: "Pharmacien",
					value: "pharmacien",
				},
			],
		};
	},
});
</script>
```

2023-10-24 09:13 UTC, DavidFyon commented
Besoin des composants: `PeriodField`, `SearchListField`, `ChipList`

2024-04-19 12:04 UTC, 4dr1en commented
j'ai modifié le playground pour se passer de `PeriodField` et `SearchListField`,

2024-04-19 13:12 UTC, DavidFyon commented
Fixer certains styles :

![Capture d’écran 2024-04-19 à 15 11 48](https://github.com/assurance-maladie-digital/design-system/assets/1822420/8bd1063a-ddd5-4e9b-8654-08d1f04af0a5)
![Capture d’écran 2024-04-19 à 15 11 43](https://github.com/assurance-maladie-digital/design-system/assets/1822420/482f17ba-0eee-4e96-b6d7-a23cae84ab26)
![Capture d’écran 2024-04-19 à 15 11 53](https://github.com/assurance-maladie-digital/design-system/assets/1822420/972e9abb-a3f9-4aa4-8c20-a6faff25e8ed)

2024-04-19 13:25 UTC, DavidFyon commented on packages/synapse-bridge/tsconfig.json
> +, "src/mixins/filterable/types.ts"	],
Pourquoi tu as du ajouter ça la ?

2024-04-19 13:40 UTC, 4dr1en commented on packages/synapse-bridge/tsconfig.json
> +, "src/mixins/filterable/types.ts"	],
ça ne semble pas être necessaire, je l'enlève.

2024-04-19 13:40 UTC, 4dr1en approved these changes

2024-05-14 15:14 UTC, VachetVirginie commented
Il n'y a pas un pb sur le playground? Tu renseigne la value des folderTypes mais le filtres n'est pas pre selectionne

2024-05-14 15:16 UTC, VachetVirginie commented
Si je selectionne 3 filtres dans types de dossiers et supprime(via la croix) celui du millieu les 2 derniers disparaissent mais le total reste a 2 
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/5d37c906-29c1-4a5e-8060-80defd0c925f)

2024-05-14 15:17 UTC, VachetVirginie requested changes
Retours en commentaire de la pr

2024-05-16 08:22 UTC, 4dr1en commented
> Si je selectionne 3 filtres dans types de dossiers et supprime(via la croix) celui du millieu les 2 derniers disparaissent mais le total reste a 2 ![image](https://private-user-images.githubusercontent.com/26382911/330495005-5d37c906-29c1-4a5e-8060-80defd0c925f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDUyMjMsIm5iZiI6MTcxNTg0NDkyMywicGF0aCI6Ii8yNjM4MjkxMS8zMzA0OTUwMDUtNWQzN2M5MDYtMjljMS00YTVlLTgwNjAtODBkZWZkMGM5MjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzN2ZmZDI0MWMzMzlkMDM0MzQ3YTk2YjUxMTBlMWJlMTcwN2NkMTZmZTVlMDBkZmFjMDU5ZGMzYWM5NzAwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpjQ83IIE1XgxY_mrYObqFddMwjo6-Gtb4MxQ4sdnLM)

j'ai corrigé l'issue

2024-05-30 15:39 UTC, VachetVirginie approved these changes

2024-05-31 11:35 UTC, merged