Form Builder
assurance-maladie-digital/design-system pull request #3247
Opened 2023-11-10 09:59 UTC by DavidFyon

Add Form Builder

2023-11-10 10:26 UTC, DavidFyon commented
Besoin des composants `PasswordField`, `DatePicker`, `PeriodField`, `RangeField`, `SelectBtnField`

2024-06-24 12:12 UTC, VachetVirginie commented
Je sais pas si ca vous fait pareil mais j'ai un pb de style sur les input 
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/b2dccfba-6fe2-4ea7-8292-b861f923b9f9)

2024-06-24 12:17 UTC, VachetVirginie requested changes
Pb de style le outlined ne fonctionne pas

2024-06-24 12:31 UTC, DavidFyon commented
> Pb de style le outlined ne fonctionne pas

ça fonctionne chez moi
![Capture d’écran 2024-06-24 à 14 27 14](https://github.com/assurance-maladie-digital/design-system/assets/1822420/ae09ef39-1e1a-423c-b3c6-1b300fb152a5)

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/FormField.vue
> +			>
Il faudrai ajouter un aria-label pour l'accessibilte

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceField.vue
> +				}
On peut simplifier: this.choiceValue = value ? value : { value: null };

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceField.vue
> +		},
On peut simplifier : 
```
		showOtherTextareaField(): boolean {
			if(!this.doOtherChoiceHaveTrigger) {
				return false;
			}

			const choiceFieldValue = this.choiceValue.value;

			if (choiceFieldValue === this.field.other?.selectedChoice) {
				return true;
			}

			if (!Array.isArray(choiceFieldValue) || !choiceFieldValue.length) {
				return false;
			}

			return choiceFieldValue.includes(this.field.other?.selectedChoice);

			
		},
```

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceField.vue
> +			:color="field.fieldOptions?.color ?? 'primary'"
Une pure beautee la liaison de données dynamique

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceSliderField.vue
> +		}
On peut faire labels(): string[] {
  return this.items && this.options
    ? this.items.map((item) => (item.title || item.text) as string)
    : [];
}

2024-06-24 12:36 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceSliderField.vue
> +		},
getIndex(value: unknown): number {
  if (!this.items) {
    return 0;
  }
  const index = this.items.findIndex((item) => item.value === value);
  return index !== -1 ? index : 0;
}

2024-06-26 08:44 UTC, 4dr1en commented on packages/synapse-bridge/src/form-builder/FormField/FormField.vue
> +			>
je pense que ça risquerais de faire doublon avec la propriété "aria-describedby" du composant

2024-06-26 12:30 UTC, VachetVirginie commented
@DavidFyon @4dr1en il faut qu'on pense a ajouter des [no-data-text](https://vuetifyjs.com/en/api/v-select/#props-no-data-text) sur les inputs concernes

2024-06-26 13:05 UTC, VachetVirginie requested changes

2024-06-26 13:05 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceField.vue
> +				this.$nextTick(() => this.$refs.otherFieldRef.focus());
this.$nextTick(() => this.$refs?.otherFieldRef?.focus());
A modifier pour faire passer les tests et eviter les pbs a l'appel de focus()

2024-06-26 13:07 UTC, VachetVirginie commented on packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceField.vue
> +	FieldItem,
Non utilise a supprimer sinon cela pose des pbs pour le build

2024-06-26 13:17 UTC, VachetVirginie approved these changes

2024-06-26 15:10 UTC, DavidFyon commented
j'ai modifié un peu le Playground pour tester l'affichage, j'ai l'impression qu'il faudrait repasser un peu sur les formField (il manque des tests aussi dans FormField>fields>tests) ?
https://digital-design-system.netlify.app/composants-techniques/formulaires/form-field

```vue
<template>
    <VApp>
       <VAppBar
          app
          dark
          color="primary"
          class="px-8"
       >
          <h1 class="text-h6">
             Playground
          </h1>
       </VAppBar>

       <VMain>
          <PageContainer>
             <!--<FormBuilder v-model="form" />
             {{ form }}-->
             <FormField v-model="field" />
             {{ field }}
          </PageContainer>
       </VMain>
    </VApp>
</template>

<script lang="ts">
import PageContainer from '@/elements/PageContainer/PageContainer.vue';
import FormBuilder from '@/form-builder/FormBuilder/FormBuilder.vue';
import FormField from '@/form-builder/FormField/FormField.vue';
import { Form } from '@/form-builder/FormBuilder/types';
import { Field } from '@/form-builder/FormField/types';
import { defineComponent } from 'vue';

export default defineComponent({
    data() {
       return {
          form: {
             informations: {
                title: 'Vos informations',
                questions: {
                   nir: {
                      type: 'text',
                      value: null,
                      fieldOptions: {
                         label: 'Numéro de Sécurité Sociale',
                         variant: 'outlined'
                      }
                   },
                   lastName: {
                      type: 'text',
                      value: null,
                      fieldOptions: {
                         label: 'Nom',
                         variant: 'outlined',
                         color: 'success'
                      }
                   },
                   firstName: {
                      type: 'text',
                      value: null,
                      fieldOptions: {
                         label: 'Prénom',
                         variant: 'outlined'
                      }
                   },
                   age: {
                      type: 'number',
                      value: null,
                      fieldOptions: {
                         label: 'Age',
                         variant: 'outlined',
                         mask: '###'
                      }
                   },
                   contact: {
                      type: 'select',
                      dynamic: true,
                      items: [
                         {
                            text: 'Email',
                            value: 'email'
                         },
                         {
                            text: 'Courrier',
                            value: 'mail'
                         },
                         {
                            text: 'SMS',
                            value: 'sms'
                         }
                      ],
                      value: null,
                      fieldOptions: {
                         label: 'Moyen de contact',
                         variant: 'outlined'
                      }
                   }
                },
             },
             health: {
                title: 'Votre état de santé',
                questions: {
                   symptoms: {
                      type: 'textarea',
                      title: 'Vos symptômes',
                      description: 'Décrivez les symptômes qui vous affectent et leur ordre d'apparition.',
                      value: null,
                      fieldOptions: {
                         label: 'Décrivez vos symptômes',
                         variant: 'outlined'
                      }
                   },
                   symptomsDate: {
                      type: 'date',
                      value: null,
                      description: 'Date d'apparition des symptômes',
                      fieldOptions: {
                         label: 'Date d'apparition',
                         outlined: true
                      }
                   }
                }
             },
             rating: {
                title: 'Votre état de santé',
                questions: {
                   rating: {
                      type: 'select',
                      items: [
                         {
                            text: 'médiocre',
                            value: 1
                         },
                         {
                            text: 'Moyenne',
                            value: 2
                         },
                         {
                            text: 'Bonne',
                            value: 3
                         },
                         {
                            text: 'Très bonne',
                            value: 4
                         }
                         ,
                         {
                            text: 'Optimal',
                            value: 5
                         }
                      ],
                      value: null,
                      fieldOptions: {
                         type: 'choiceSlider',
                         label: 'Etat de santé',
                         hideDetails: true,
                         thumbLabel: true,
                         thumbSize: '20px'
                      }
                   },
                   choice: {
                      type: 'select',
                      items: [
                         {
                            text: 'Oui',
                            value: 'yes'
                         },
                         {
                            text: 'Non',
                            value: 'no'
                         }
                      ],
                      value: null,
                      fieldOptions: {
                         type: 'choiceButton',
                         label: 'Avez-vous des antécédents médicaux ?',
                      }
                   },
                   choice2: {
                      type: 'select',
                      items: [
                         {
                            text: 'Demangeaison',
                            value: 'Demangeaison'
                         },
                         {
                            text: 'Toux',
                            value: 'Toux'
                         },
                         {
                            text: 'Fièvre',
                            value: 'Fièvre'
                         },
                         {
                            text: 'Maux de tête',
                            value: 'Maux de tête'
                         },
                         {
                            text: 'Courbatures',
                            value: 'Courbatures'
                         },
                         {
                            text: 'Perte de gout',
                            value: 'Perte de gout'
                         },
                         {
                            text: 'Perte d'odorat',
                            value: 'Perte d'odorat'
                         },
                         {
                            text: 'Difficultés respiratoires',
                            value: 'Difficultés respiratoires'
                         },
                         {
                            text: 'Autre',
                            value: 'Autre'
                         }
                      ],
                      value: null,
                      fieldOptions: {
                         type: 'choiceAutocomplete',
                         label: 'De quoi souffrez vous ?',
                         variant: 'outlined'
                      }
                   }
                }
             }
          } as Form,
        [...]

2024-07-01 16:17 UTC, 4dr1en commented
> j'ai modifié un peu le Playground pour tester l'affichage, j'ai l'impression qu'il faudrait repasser un peu sur les formField (il manque des tests aussi dans FormField>fields>tests) ? https://digital-design-system.netlify.app/composants-techniques/formulaires/form-field
> 
> ```
> <template>
>     <VApp>
>        <VAppBar
>           app
>           dark
>           color="primary"
>           class="px-8"
>        >
>           <h1 class="text-h6">
>              Playground
>           </h1>
>        </VAppBar>
> 
>        <VMain>
>           <PageContainer>
>              <!--<FormBuilder v-model="form" />
>              {{ form }}-->
>              <FormField v-model="field" />
>              {{ field }}
>           </PageContainer>
>        </VMain>
>     </VApp>
> </template>
> 
> <script lang="ts">
> import PageContainer from '@/elements/PageContainer/PageContainer.vue';
> import FormBuilder from '@/form-builder/FormBuilder/FormBuilder.vue';
> import FormField from '@/form-builder/FormField/FormField.vue';
> import { Form } from '@/form-builder/FormBuilder/types';
> import { Field } from '@/form-builder/FormField/types';
> import { defineComponent } from 'vue';
> 
> export default defineComponent({
>     data() {
>        return {
>           form: {
>              informations: {
>                 title: 'Vos informations',
>                 questions: {
>                    nir: {
>                       type: 'text',
>                       value: null,
>                       fieldOptions: {
>                          label: 'Numéro de Sécurité Sociale',
>                          variant: 'outlined'
>                       }
>                    },
>                    lastName: {
>                       type: 'text',
>                       value: null,
>                       fieldOptions: {
>                          label: 'Nom',
>                          variant: 'outlined',
>                          color: 'success'
>                       }
>                    },
>                    firstName: {
>                       type: 'text',
>                       value: null,
>                       fieldOptions: {
>                          label: 'Prénom',
>                          variant: 'outlined'
>                       }
>                    },
>                    age: {
>                       type: 'number',
>                       value: null,
>                       fieldOptions: {
>                          label: 'Age',
>                          variant: 'outlined',
>                          mask: '###'
>                       }
>                    },
>                    contact: {
>                       type: 'select',
>                       dynamic: true,
>                       items: [
>                          {
>                             text: 'Email',
>                             value: 'email'
>                          },
>                          {
>                             text: 'Courrier',
>                             value: 'mail'
>                          },
>                          {
>                             text: 'SMS',
>                             value: 'sms'
>                          }
>                       ],
>                       value: null,
>                       fieldOptions: {
>                          label: 'Moyen de contact',
>                          variant: 'outlined'
>                       }
>                    }
>                 },
>              },
>              health: {
>                 title: 'Votre état de santé',
>                 questions: {
>                    symptoms: {
>                       type: 'textarea',
>                       title: 'Vos symptômes',
>                       description: 'Décrivez les symptômes qui vous affectent et leur ordre d'apparition.',
>                       value: null,
>                       fieldOptions: {
>                          label: 'Décrivez vos symptômes',
>                          variant: 'outlined'
>                       }
>                    },
>                    symptomsDate: {
>                       type: 'date',
>                       value: null,
>                       description: 'Date d'apparition des symptômes',
>                       fieldOptions: {
>                          label: 'Date d'apparition',
>                          outlined: true
>                       }
>                    }
>                 }
>              },
>              rating: {
>                 title: 'Votre état de santé',
>                 questions: {
>                    rating: {
>                       type: 'select',
>                       items: [
>                          {
>                             text: 'médiocre',
>                             value: 1
>                          },
>                          {
>                             text: 'Moyenne',
>                             value: 2
>                          },
>                          {
>                             text: 'Bonne',
>                             value: 3
>                          },
>                          {
>                             text: 'Très bonne',
>                             value: 4
>                          }
>                          ,
>                          {
>                             text: 'Optimal',
>                             value: 5
>                          }
>                       ],
>                       value: null,
>                       fieldOptions: {
>                          type: 'choiceSlider',
>                          label: 'Etat de santé',
>                          hideDetails: true,
>                          thumbLabel: true,
>                          thumbSize: '20px'
>                       }
>                    },
>                    choice: {
>                       type: 'select',
>                       items: [
>                          {
>                             text: 'Oui',
>                             value: 'yes'
>                          },
>                          {
>                             text: 'Non',
>                             value: 'no'
>                          }
>                       ],
>                       value: null,
>                       fieldOptions: {
>                          type: 'choiceButton',
>                          label: 'Avez-vous des antécédents médicaux ?',
>                       }
>                    },
>                    choice2: {
>                       type: 'select',
>                       items: [
>                          {
>                             text: 'Demangeaison',
>                             value: 'Demangeaison'
>                          },
>                          {
>                             text: 'Toux',
>                             value: 'Toux'
>                          },
>                          {
>                             text: 'Fièvre',
>                             value: 'Fièvre'
>                          },
>                          {
>                             text: 'Maux de tête',
>                             value: 'Maux de tête'
>                          },
>                          {
>                             text: 'Courbatures',
>                             value: 'Courbatures'
>                          },
>                          {
>                             text: 'Perte de gout',
>                             value: 'Perte de gout'
>                          },
>                          {
>                             text: 'Perte d'odorat',
>                             value: 'Perte d'odorat'
>                          },
>                          {
>                             text: 'Difficultés respiratoires',
>                             value: 'Difficultés respiratoires'
>                          },
>                          {
>                             text: 'Autre',
 [...]

2024-07-02 14:12 UTC, DavidFyon commented
Faudra checker le range value, le valeurs retournées devraient être arrondies non ?
![capture_d___e__cran_2024-07-02_a___16 09 32_720](https://github.com/assurance-maladie-digital/design-system/assets/1822420/2b5ec254-f6fc-45d3-9d42-d972bf612542)

```vue
field: {
    type: 'range',
    min: 0,
    max: 100,
    value: null,
    fieldOptions: {
       outlined: true
    }
} as Field
```

2024-07-02 14:15 UTC, DavidFyon commented
Le calendrier est décalé :

![Capture d’écran 2024-07-02 à 16 14 39](https://github.com/assurance-maladie-digital/design-system/assets/1822420/d156a14f-fdcc-4e95-a14a-b2a6d289fada)

```vue
field: {
  type: 'date',
  value: null,
  fieldOptions: {
	  label: 'Votre date de naissance',
	  outlined: true
  }
  } as Field
```

2024-07-02 14:18 UTC, DavidFyon commented
le outlined n'est pas bon sur le textarea :

![Capture d’écran 2024-07-02 à 16 17 31](https://github.com/assurance-maladie-digital/design-system/assets/1822420/3dc24c3f-ca32-4c24-be24-5de9eeddce33)

```vue
field: {
				type: 'textarea',
				title: 'Vos symptômes',
				description: 'Décrivez les symptômes qui vous affectent et leur ordre d’apparition.',
				value: null,
				fieldOptions: {
					label: 'Décrivez vos symptômes',
					hideDetails: true,
					outlined: true
				}
			} as Field
```

2024-07-02 15:43 UTC, 4dr1en commented
> ```
> {
>     type: 'range',
>     min: 0,
>     max: 100,
>     value: null,
>     fieldOptions: {
>        outlined: true
>     }
> }
> ```

fixed

2024-07-02 15:49 UTC, 4dr1en commented
> ```
> {
>   type: 'date',
>   value: null,
>   fieldOptions: {
> 	  label: 'Votre date de naissance',
> 	  outlined: true
>   }
>   }
> ```

done

2024-07-02 15:50 UTC, 4dr1en commented
> le outlined n'est pas bon sur le textarea, text, number, select :
> 
> ![Capture d’écran 2024-07-02 à 16 17 31](https://private-user-images.githubusercontent.com/1822420/345068624-3dc24c3f-ca32-4c24-be24-5de9eeddce33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzExODMsIm5iZiI6MTcxOTkzMDg4MywicGF0aCI6Ii8xODIyNDIwLzM0NTA2ODYyNC0zZGMyNGMzZi1jYTMyLTRjMjQtYmUyNC01ZGU5ZWVkZGNlMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTQzNDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzgzZWZmZWMyNjFmMTRjNmE5MzQ0ZTFhMWFkOWQ4MGY5NjFkYTViMDI1YzVmYWU4ZjJmODQ4YTA5YTljNzU5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k2nHTwb7Fl0fnrETuvkgcIrsjCt5HWr3msXjKuaHepg)
> 
> ```
> field: {
> 				type: 'textarea',
> 				title: 'Vos symptômes',
> 				description: 'Décrivez les symptômes qui vous affectent et leur ordre d’apparition.',
> 				value: null,
> 				fieldOptions: {
> 					label: 'Décrivez vos symptômes',
> 					hideDetails: true,
> 					outlined: true
> 				}
> 			} as Field
> ```
> 
> ```
> field: {
> 				type: 'text',
> 				value: null,
> 				fieldOptions: {
> 					label: 'Votre nom',
> 					hideDetails: true,
> 					outlined: true
> 				}
> 			} as Field
> ```
> 
> ```
> field: {
> 				type: 'number',
> 				value: null,
> 				fieldOptions: {
> 					label: 'Votre âge',
> 					hideDetails: true,
> 					outlined: true,
> 					mask: '###'
> 				}
> 			} as Field
> ```
> 
> ```
> field: {
> 				type: 'select',
> 				dynamic: true,
> 				items: [
> 					{
> 						text: 'Email',
> 						value: 'email'
> 					},
> 					{
> 						text: 'Courrier',
> 						value: 'mail'
> 					},
> 					{
> 						text: 'SMS',
> 						value: 'sms'
> 					}
> 				],
> 				value: null,
> 				fieldOptions: {
> 					label: 'Moyen de contact',
> 					hideDetails: true,
> 					outlined: true
> 				}
> 			} as Field
> ```

avec vuetify 3, c'est 'variant: outlined'

2024-07-03 12:52 UTC, VachetVirginie approved these changes

2024-07-03 12:55 UTC, 4dr1en approved these changes

2024-07-03 13:50 UTC, VachetVirginie approved these changes

2024-07-03 13:51 UTC, merged