💄vue-dot : Alert font size
assurance-maladie-digital/design-system pull request #3292
Opened 2023-12-18 14:13 UTC by 4dr1en

## Description

Utilisation de la font en taille 18px '1.125rem' pour les Alertes pour coller avec la charte figma

## Playground

<details>

```vue
<template>
	<PageContainer>
		<AlertWrapper>
			Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores inventore, reiciendis obcaecati voluptates repellat ut cumque dolor dolore possimus alias mollitia ex iusto sit cupiditate delectus quis ipsum fuga quibusdam?
		</AlertWrapper>
	</PageContainer>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
	components: {
	}
});
</script>

```

</details>

## Type de changement

- Maintenance

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2023-12-18 14:25 UTC, DavidFyon requested changes

2023-12-18 14:25 UTC, DavidFyon commented on packages/vue-dot/dev/App.vue
> -	@import '../src/styles/index.scss';
Enlever

2023-12-18 14:25 UTC, DavidFyon commented on packages/vue-dot/src/styles/vuetify.scss
> +.v-alert {
Utiliser les variables sass plutôt : https://v2.vuetifyjs.com/en/api/v-alert/#slots
dans le fichier variables.scss

![Capture d’écran 2023-12-18 à 15 23 54](https://github.com/assurance-maladie-digital/design-system/assets/1822420/ddb2dea5-3bb4-478a-9d3c-47389f0f4a17)

2023-12-18 14:57 UTC, DavidFyon approved these changes

2023-12-18 14:58 UTC, 4dr1en commented on packages/vue-dot/src/styles/vuetify.scss
> +.v-alert {
done

2024-01-09 16:59 UTC, deraw commented on packages/vue-dot/dev/App.vue
> -	@import '../src/styles/index.scss';
Pourquoi avoir supprimé cet import ?

2024-01-09 18:04 UTC, 4dr1en commented on packages/vue-dot/dev/App.vue
> -	@import '../src/styles/index.scss';
J'ai constaté que cette ligne condusait à la duplication du style dans les source, ce style étant déjà importé [ici](https://github.com/assurance-maladie-digital/design-system/blob/50ae03daed6befaf8e5d4e26f76c2891c24ccc5e/packages/vue-dot/src/index.ts#L10)

2024-01-10 13:32 UTC, deraw commented on packages/vue-dot/src/styles/variables.scss
> +$alert-font-size: map-get( $headings, 'body-1', 'size');
```suggestion
$alert-font-size: map-get($headings, 'body-1', 'size');
```

2024-01-10 13:32 UTC, deraw approved these changes

2024-01-10 15:06 UTC, merged