Fix a typescript warning in LogoBrandSection
assurance-maladie-digital/design-system pull request #3336
Opened 2024-01-15 10:33 UTC by 4dr1en

## Description

Permettre a typescript de comprendre que le titre est de type `HighlightedTitle` quand le thème est de type compteEntreprise.

## Playground

<details>

```vue
<template>
	<PageContainer>
		<LogoBrandSection
			theme="compte-entreprise"
		/>
	</PageContainer>
</template>

<script lang="ts">
	import Component from 'vue-class-component';
	import Vue from 'vue';

	@Component
	export default class FilePreviewUsage extends Vue {}
</script>

```

</details>

## Type de changement

- Correction de bug

## Checklist

- [x] Ma Pull Request pointe vers la bonne branche
- [x] Mon code suit le style de code du projet
- [x] J'ai effectué une review de mon propre code
- [x] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [x] J'ai apporté les modifications correspondantes à la documentation
- [x] Mes modifications ne génèrent aucun nouveau warning
- [x] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [x] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-01-15 10:48 UTC, DavidFyon approved these changes

2024-01-17 13:17 UTC, deraw requested changes

2024-01-17 13:17 UTC, deraw commented on packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
> +		}
Je ne suis pas fan de cette fonction, il doit y avoir moyen de corriger le type sans créer une fonction pour non ? D'où vient le warning exactement ?

2024-01-22 09:36 UTC, 4dr1en commented on packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
> +		}
Le composant attend que la props title soit de type `HightlightedTitle` quand le thème est défini sur compte entreprise. Mais typescript n'est pas capable de comprendre cette relation.
Le but de cette pr est de faire comprendre a typescript que le type de title est `HightlightedTitle` dans cette situation.

Une solution qui n'impliquerai pas de créé une fonction dédié serait celle ci dans un ancien commit :
https://github.com/assurance-maladie-digital/design-system/pull/3336/commits/31caafcb0d7a81e5e4d2170868d109f698ad235d

2024-01-24 03:25 UTC, closed without merging

2024-01-24 03:25 UTC, deraw commented
Il y a une erreur dans l'IDE puisqu'on utilise Volar mais ce n'est pas une erreur à corriger en soit, ça ne gêne ni le build ni le fonctionnement du composant, on verra ça en v3.