Initialisation de la v3 du bridge
assurance-maladie-digital/design-system pull request #3377
Opened 2024-01-29 09:05 UTC by 4dr1en

## Description

Initialisation de la version 3 du ds

## Type de changement

- Nouvelle fonctionnalité
- Changement cassant
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-01-29 09:21 UTC, DavidFyon commented
Dans `dev` tu peux rajouter le Playground

2024-01-29 09:39 UTC, DavidFyon requested changes
<img width="876" alt="Capture d’écran 2024-01-29 à 10 45 09" src="https://github.com/assurance-maladie-digital/design-system/assets/1822420/7c1ef38b-a536-4eb0-8422-a3081bfb2f96">

- Dans `dev` tu peux rajouter le Playground
- Dans `src` tu peux rajouter les dossiers patterns, templates, composables, services... (comme pour le bridge sauf les mixins)
- Dossier scripts

2024-01-29 13:39 UTC, DavidFyon approved these changes
@deraw @christopheGaon  Prévoir le setup Lerna pour ce package

2024-02-06 17:10 UTC, deraw commented
@4dr1en Il faut renommer le package en `synapse`

2024-02-06 17:13 UTC, deraw requested changes
J'ai commencé rapidement la review mais avant de continuer je me demande pourquoi est-ce qu'on ne part de ce qui est fait sur le bridge ?

2024-02-06 17:13 UTC, deraw commented on packages/design-system-v3/.prettierrc.json
Pourquoi est-ce qu'il y a Prettier ?

2024-02-06 17:13 UTC, deraw commented on packages/design-system-v3/README.md
Il faut mettre à jour ce Readme et l'écrire en français

2024-02-06 17:13 UTC, deraw commented on packages/design-system-v3/dev/main.ts
Pourquoi ne pas reprendre ce qui est fait sur le bridge ?

2024-02-06 17:13 UTC, deraw commented on packages/design-system-v3/dev/stores/example.ts
Quel est l'intérêt de ce fichier ?

2024-02-07 10:19 UTC, 4dr1en commented
> ent la review mais avant de continuer je me demande pourquoi est-ce qu'on ne part de ce qui est fait sur le bridge ?

Merci pour tes retours, cette branche se veux également un support de discussion pour arrêter certaines décisions et garder une cohérence dans le futur.
- La syntaxe des composants (syntax typescript pour la définition des props, utilisation de defineModel ...)
- La syntaxe des stores (option ou composition)
- L'utilisation de prettier pour faire face a [la dépréciation des règles de formattages par eslint](https://eslint.org/blog/2023/10/deprecating-formatting-rules/) (dans la ligné de ce qu'à [déja fait stylelint](https://stylelint.io/migration-guide/to-15/) par example)

Pour cette v3, Nous nous sommes déjà arrèté sur un certain nombre de décision : 
- passage à la composition api pour les composants (voir la rfc de @DavidFyon )
- le refonte de toutes les mixines pour passer sur l'utilisation de composables
- passage de VueX à Pinia
- Changement des typos
- Passage à Node20

Le but est également d'utiliser autant que possible la dernière version des librairies que nous utilisons.

Il m'a semblé préférable de regénérer le projet pour avoir une configuration la plus à jour possible et utiliser les dernières consiges de setups pour l'import des librairies. La dépréciation de "@invictus.codes/nuxt-vuetify" pour les SK nous à montré que ce sont des éléments qui pouvaient évoluer assez vite, au délà des changements que j'ai listé. Au delà de ces changements le but est d'être le plus proche que possible de la version bridge. N'hésitez pas a proposer tout changements pour cela.

@deraw @DavidFyon @VachetVirginie

2024-07-22 07:27 UTC, closed without merging