🩹vue-dot: Fix two way data binding on LangBtn value
assurance-maladie-digital/design-system pull request #3386
Opened 2024-02-07 14:52 UTC by 4dr1en

## Description

Faire en sorte que l'affichage du boutton se met a jour si la valeur de la langue est mise a jour de façon externe

## Playground

<details>

```vue
<template>
	<div>
		<LangBtn
			v-model="lang"
			:available-languages="[
				'fr',
				'en',
				'de',
				'zh'
			]"
		/>
		{{ lang }}
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class LangBtnAvailableLanguages extends Vue {
		lang = 'fr';

		mounted() {
			setTimeout(() => {
				this.lang = 'toto';
			}, 1000);
		}
	}
</script>

```

</details>

## Type de changement

- Correction de bug

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-02-07 20:07 UTC, DavidFyon requested changes
2 soucis que j'ai vu :
- le bouton est noir, il devrait être bleu en outline je pense
- il y a un bug dans la doc quand on désélectionne la langue courante (à tester dans le composant aussi) :
<img width="680" alt="Capture d’écran 2024-02-07 à 21 04 43" src="https://github.com/assurance-maladie-digital/design-system/assets/1822420/2ffe2c72-cb88-4b98-aa7f-5a07d1538b12">

2024-02-08 09:12 UTC, 4dr1en commented
> * il y a un bug dans la doc quand on désélectionne la langue courante (à tester dans le composant aussi) :

j'ai passé un nouveau commit pour fixer ce problème également.

2024-02-08 09:17 UTC, DavidFyon commented
@4dr1en Sur le Figma c'est en bleu 
Je vais te refaire le visu pour la miniature
![Capture d’écran 2024-02-08 à 10 16 50](https://github.com/assurance-maladie-digital/design-system/assets/1822420/0e517e64-078d-403f-993a-a6bb5f4348aa)

2024-02-08 09:47 UTC, 4dr1en commented
done @DavidFyon

2024-02-09 15:13 UTC, VachetVirginie approved these changes

2024-02-09 15:20 UTC, DavidFyon approved these changes

2024-03-05 13:50 UTC, deraw approved these changes

2024-03-05 13:51 UTC, deraw commented
J'ai inversé la condition dans le handler pour `availableLanguages` afin de simplifier le code

2024-03-05 13:53 UTC, merged