WIP add headerBar
assurance-maladie-digital/design-system pull request #3395
Opened 2024-02-14 14:44 UTC by VachetVirginie

## Description
Components manquants: 

 - BackBtn
 - UserBtn

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/elements/LogoBrandSection/LogoBrandSection.vue
Est-ce que les changements dans ce composant sont voulus ?

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/elements/UserMenuBtn/tests/UserMenuBtn.spec.ts
> +import {fail} from "assert";
Cet import n'est pas utilisé, si ?

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/elements/UserMenuBtn/tests/UserMenuBtn.spec.ts
> +	// });
À supprimer, il faut éviter de laisser du code mort

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/elements/UserMenuBtn/UserMenuBtn.vue
Est-ce que les changements ici sont voulus aussi ?

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationBar/tests/HeaderNavigationBar.spec.ts
> +		expect(result).toBe("#0a347b"); // Ensure it returns default color
```suggestion
		const result = wrapper.vm.backgroundColor;

		expect(result).toBe("#0a347b");
```

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationBar/tests/HeaderNavigationBar.spec.ts
> +		// Arrange
```suggestion
```

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationBar/tests/HeaderNavigationBar.spec.ts
> +		}
Il ne faut pas mettre l'assertion dans une condition, le test doit échouer si la condition n'est pas remplie

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationDrawer/tests/__snapshots__/HeaderNavigationDrawer.spec.ts.snap
Il faudrait ajouter un test avec des données

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/ThemeEnum.ts
On peut supprimer ce fichier non ?

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/tests/HeaderBar.spec.ts
Je pense que ça peut être bien ici d'imbriquer des blocs `describe` pour les différentes parties comme `fullHeight` ou `showNavigationBar`

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Je pense qu'il faudrait monter le composant complètement afin d'avoir de vraies snapshots

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/types.d.ts
> +	label: string;
```suggestion
	label: string;
	href?: string;
```
Histoire d'avoir les propriétés obligatoires en premier

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/router/index.ts
Pourquoi ajouter ce fichier dans `src` ? Il devrait être dans `dev` non ?

2024-03-10 00:37 UTC, deraw commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue
> +  <v-app>
Il me semble qu'il ne faut qu'un seul `VApp` par application, il faut le supprimer sinon ça risque de poser problème

2024-03-10 04:22 UTC, VachetVirginie commented on packages/synapse-bridge/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue
> +  <v-app>
@VachetVirginie check pb rebase

2024-03-13 09:52 UTC, DavidFyon approved these changes

2024-03-13 10:23 UTC, 4dr1en requested changes
![Screenshot 2024-03-13 at 11-20-25 Synapse Bridge Playground](https://github.com/assurance-maladie-digital/design-system/assets/65124433/e01754f0-ff28-4d8e-88a5-fa838a805208)
Le scroll devrait etre bloqué quand le menu est ouvert

2024-03-13 10:31 UTC, 4dr1en commented
les couleures du menu sont pas iso a la v2
![Screenshot 2024-03-13 at 11-29-24 Synapse Bridge Playground](https://github.com/assurance-maladie-digital/design-system/assets/65124433/2b2b6df7-15d1-4618-b53c-523b9104bc2a)
![Screenshot 2024-03-13 at 11-29-44 HeaderBar](https://github.com/assurance-maladie-digital/design-system/assets/65124433/90c19884-7c94-4964-b2b5-3ad1b1460cb8)

2024-03-13 14:54 UTC, 4dr1en commented
dans le menu le style d'un bouton selectionné a changé:
![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/d928cefa-cbf2-4144-a77d-51205ee562ec)
![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/60f2bcd5-787d-46b7-b4aa-e3a3aef56302)

En mode mobile également

![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/3e2daa9d-e0c6-429e-aed3-8df653a7a4d4)
![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/3634265a-32a7-4940-bbac-ea42d3e43b84)

L'animation de transition de la barre blanche vertical entre les bouttons à également changé.
Je ne sais pas dans quelle mesure ces changements sont volontaires..

2024-03-13 14:56 UTC, 4dr1en requested changes
à voire si les changements de style doivent étres conservés.

J'ai toujours le problème de l'overlay du menu qui ne prend pas toute la hauteur quand on ouvre le menu après avoir un peu scrollé

2024-03-13 15:51 UTC, VachetVirginie commented
> dans le menu le style d'un bouton selectionné a changé: ![image](https://private-user-images.githubusercontent.com/65124433/312504926-d928cefa-cbf2-4144-a77d-51205ee562ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDI4MjgsIm5iZiI6MTcxMDM0MjUyOCwicGF0aCI6Ii82NTEyNDQzMy8zMTI1MDQ5MjYtZDkyOGNlZmEtY2JmMi00MTQ0LWE3N2QtNTEyMDVlZTU2MmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjE4YTdkNjY3MzMyOTk2MjExOGIyYThlZTVkNGI2OGViM2RhMDA2MjEzOGY3M2U5MTIwY2JlMGFiYmMyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TfiipbEH3R12TkA7VvN8Fvl0LRllo8DqiklCs2soDnE) ![image](https://private-user-images.githubusercontent.com/65124433/312505036-60f2bcd5-787d-46b7-b4aa-e3a3aef56302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDI4MjgsIm5iZiI6MTcxMDM0MjUyOCwicGF0aCI6Ii82NTEyNDQzMy8zMTI1MDUwMzYtNjBmMmJjZDUtNzg3ZC00NmI3LWI0YWEtZTNhM2FlZjU2MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYWZhOGNlZjQ2NDQ1ZTIxN2ZmZGY4NGQ0MzkxZGRjYzM0MTk2OWI0NTBlNzI5MWIzMWQ4MDFjZmU0ZmIwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdKuj_QnCAKDTjqxiy8DjeCRSXU_AtSVuATBsWKry5U)
> 
> En mode mobile également
> 
> ![image](https://private-user-images.githubusercontent.com/65124433/312505306-3e2daa9d-e0c6-429e-aed3-8df653a7a4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDI4MjgsIm5iZiI6MTcxMDM0MjUyOCwicGF0aCI6Ii82NTEyNDQzMy8zMTI1MDUzMDYtM2UyZGFhOWQtZTBjNi00MjllLWFlZDMtOGRmNjUzYTdhNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOWQ4NmJmN2IzM2NlZTZmZWI1NDM2N2U5ZmVmYTQxMmUzYTMxYjI4ODBhOTQ3MjUyNjk2NjNkZDU3Y2RlMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hv5PTvvyQQX94XAcOCu0JPOGxSKwHGptX8af8gfvKUE) ![image](https://private-user-images.githubusercontent.com/65124433/312505384-3634265a-32a7-4940-bbac-ea42d3e43b84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDI4MjgsIm5iZiI6MTcxMDM0MjUyOCwicGF0aCI6Ii82NTEyNDQzMy8zMTI1MDUzODQtMzYzNDI2NWEtMzJhNy00OTQwLWJiYWMtZWE0MmQzZTQzYjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNzdiODE0MjQ1NDI4ZTAwOTE2YjU1OGE4MTJjMjc0OTMwMDgyMzRjYWZjY2U3YjI1YTY2YThhYjFmOGRlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E2bQltCYuCeEvsP4hVMMjmbLEszf0BsL91vjBJ7pgmY)
> 
> L'animation de transition de la barre blanche vertical entre les bouttons à également changé. Je ne sais pas dans quelle mesure ces changements sont volontaires..

2024-03-13 16:09 UTC, 4dr1en approved these changes

2024-03-13 16:38 UTC, merged

2024-03-13 16:38 UTC, 4dr1en commented on packages/synapse-bridge/vite.config.ts
> +			__VUE_PROD_HYDRATION_MISMATCH_DETAILS__: false
a quoi sert cette ligne ?