♿️vue-dot: Refactor footer links to use unordered list
assurance-maladie-digital/design-system pull request #3431
Opened 2024-03-08 09:48 UTC by 4dr1en

## Description

Utiliser des listes pour améliorer l'accessibilité

## Playground

<details>

```vue
<template>
	<VApp>
		<PageContainer>
			<FooterBar v-bind="docProps" />

			<br><br>

			<FooterBar v-bind="docProps">
				<p class="text--secondary mb-0">
					Contenu supplémentaire.
				</p>
			</FooterBar>

			<br><br>

			<FooterBar
				v-bind="docProps"
				hide-sitemap-link
			>
				<p class="text--secondary mb-0">
					Contenu supplémentaire.
				</p>
			</FooterBar>

			<br><br>

			<FooterBar
				v-bind="docProps"
				class="theme--dark"
			>
				<VRow class="max-width-none">
					<VCol
						cols="12"
						sm="6"
					>
						<CollapsibleList
							:items="remboursementItems"
							list-title="Remboursement"
							class="theme--dark"
						/>
					</VCol>

					<VCol
						cols="12"
						sm="6"
					>
						<CollapsibleList
							:items="healthItems"
							list-title="Santé"
							class="theme--dark"
						/>
					</VCol>
				</VRow>
			</FooterBar>
		</PageContainer>
	</VApp>
</template>

<script lang="ts">
	import { defineComponent } from 'vue';

	import PageContainer from '../src/elements/PageContainer/PageContainer.vue';
	import FooterBar from '../src/patterns/FooterBar/FooterBar.vue';
	import CollapsibleList from '../src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue';
	import { ListItem } from '../src/patterns/FooterBar/CollapsibleList/types';

	export default defineComponent({
		components: {
			PageContainer,
			FooterBar,
			CollapsibleList
		},
		data() {
			return {
				docProps: {
					sitemapRoute: '/',
					cguRoute: '/',
					cookiesRoute: '/',
					legalNoticeRoute: '/',
					a11yStatementRoute: '/'
				},
				remboursementItems: [
					{
						text: 'Ce qui est remboursé',
						href: 'https://www.ameli.fr/assure/remboursements/rembourse'
					},
					{
						text: 'Ce qui reste à votre charge',
						href: 'https://www.ameli.fr/assure/remboursements/reste-charge'
					},
					{
						text: 'Être bien remboursé',
						href: 'https://www.ameli.fr/assure/remboursements/etre-bien-rembourse'
					}
				] as ListItem[],

				healthItems: [
					{
						text: 'Mon espace santé',
						href: 'https://www.ameli.fr/assure/sante/mon-espace-sante'
					},
					{
						text: 'Accomplir les bons gestes',
						href: 'https://www.ameli.fr/assure/sante/bons-gestes'
					},
					{
						text: 'Réagir en cas d’urgence',
						href: 'https://www.ameli.fr/assure/sante/urgence'
					},
					{
						text: 'Télésanté',
						href: 'https://www.ameli.fr/assure/sante/telesante'
					}
				] as ListItem[]
			};
		}
	});
</script>

```

</details>

## Type de changement

- Correction de bug

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-03-08 12:36 UTC, DavidFyon requested changes
Revoir l'affichage :
![Capture d’écran 2024-03-08 à 13 35 12](https://github.com/assurance-maladie-digital/design-system/assets/1822420/741c3930-f651-4a19-9e6a-58159607784a)

Se référer à : https://digital-design-system.netlify.app/composants/structure/footer-bar

2024-03-13 12:55 UTC, VachetVirginie commented
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/34c621db-8219-49a4-baa5-65a6f0e1e322)
![image](https://github.com/assurance-maladie-digital/design-system/assets/26382911/594f50e8-09ce-4993-bc67-5eec8560e20b) Je crois qu'il y a un pb sur la data de l'accessibilite

2024-03-13 12:57 UTC, VachetVirginie requested changes
cf capture

2024-03-13 13:27 UTC, 4dr1en commented
> ![image](https://private-user-images.githubusercontent.com/26382911/312462852-34c621db-8219-49a4-baa5-65a6f0e1e322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzUwMzgsIm5iZiI6MTcxMDMzNDczOCwicGF0aCI6Ii8yNjM4MjkxMS8zMTI0NjI4NTItMzRjNjIxZGItODIxOS00OWE0LWJhYTUtNjVhNmYwZTFlMzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEyNTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZTU3M2NhNDNiNTY2NDU5ZDZjYTQzYmI5ODYzNTEzZjAwZjA2MGY0MDc3NWU3YTM4MTQ5ODExZWE5ODY4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQkM_cxO5Viu5Bif5UTlHb_3E-ve9abv2b_XHS11zLQ) ![image](https://private-user-images.githubusercontent.com/26382911/312463873-594f50e8-09ce-4993-bc67-5eec8560e20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzUwMzgsIm5iZiI6MTcxMDMzNDczOCwicGF0aCI6Ii8yNjM4MjkxMS8zMTI0NjM4NzMtNTk0ZjUwZTgtMDljZS00OTkzLWJjNjctNWVlYzg1NjBlMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEyNTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYjI1ZGZmNTgxMWZmNDNkMTQ5MjQwOTVhOTBlMDIwMjAyMGEwZjMyYjgzNGE5N2U3OWMwYTVhOGY4ZmYwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjyb7Cp493iZYoNoTb8VcvWyPJMMcphSAtIzLeomzi0) Je crois qu'il y a un pb sur la data de l'accessibilite

ça me semble être le comportement normal de retour a la ligne, quand la fenètre est plus large tout est sur la même ligne
![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/6416392f-9abb-47ec-b7bc-201a3bfd123a)

2024-03-14 11:03 UTC, DavidFyon approved these changes

2024-03-22 08:11 UTC, VachetVirginie approved these changes

2024-03-27 14:40 UTC, merged