add linter
assurance-maladie-digital/design-system pull request #3561
Opened 2024-07-02 11:49 UTC by DavidFyon

## Description

## Playground

<details>

```vue
// Copiez-collez le contenu de votre Playground.vue entier ici
```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-07-04 14:03 UTC, 4dr1en requested changes
rendez moi mes points virgules

2024-07-04 14:12 UTC, 4dr1en requested changes

2024-07-04 14:12 UTC, 4dr1en commented on packages/synapse-bridge/prettier.config.js
> +	semi: false,
```suggestion
	semi: true,
```

2024-07-04 14:17 UTC, DavidFyon commented on packages/synapse-bridge/prettier.config.js
> +	semi: false,
less is more

2024-07-05 08:20 UTC, VachetVirginie approved these changes

2024-07-05 08:36 UTC, merged