Bridge/fix nirfield reactivity
assurance-maladie-digital/design-system pull request #3615
Opened 2024-07-17 10:30 UTC by 4dr1en

## Description

fix des problème de réactivité avec v-model

## Playground

<details>

```vue<template>
	<NirField v-model='value1'/>
	{{ value1 }}

	<NirField v-model='value2' :nirLength='13'/>
	{{ value2 }}
</template>

<script lang="ts">

import NirField from "@/patterns/NirField/NirField.vue";
import {defineComponent} from "vue";
;

export default defineComponent({
	components: {
		NirField
	},
	data() {
		return {
			value1: '012345678912345',
			value2: '',
		}
	},
	mounted() {
		setTimeout(() => {
			this.value1 = '012345678912345'
		}, 1000);
		setTimeout(() => {
			this.value1 = '012345678912777'
		}, 2000);

		setTimeout(() => {
			this.value1 = '012345678978945'
		}, 3000);

		setTimeout(() => {
			this.value1 = '012345678912399'
		}, 4000);

		setTimeout(() => {
			this.value1 = '012345678912345'
		}, 5000);

		setTimeout(() => {
			this.value1 = 'ABCD1234567890'
		}, 6000);
	}
});
</script>

```

</details>

## Type de changement

- Correction de bug

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-07-17 12:57 UTC, DavidFyon requested changes

2024-07-17 13:28 UTC, DavidFyon commented
Sur le dernier setTimout() le 0 se met dans la key au lieu du number

2024-07-17 15:29 UTC, 4dr1en commented on packages/synapse-bridge/package.json
> +		"./rules/*": "./src/rules/*/index.ts"
done

2024-07-18 13:00 UTC, VachetVirginie approved these changes

2024-07-18 13:17 UTC, VachetVirginie requested changes
Vu ensemble

2024-07-18 14:41 UTC, DavidFyon approved these changes

2024-07-18 14:57 UTC, VachetVirginie approved these changes

2024-07-18 14:58 UTC, merged