dialog box focus dynamic elements
assurance-maladie-digital/design-system pull request #3713
Opened 2024-08-20 10:04 UTC by 4dr1en

## Description

Permettre de gérer la tabulation quand les éléments focusables sont dynamiques
## Playground

<details>

```vue
<script setup lang="ts">
import DialogBox from '@/elements/DialogBox/DialogBox.vue'
import { onMounted, ref } from 'vue'
import { VBtn } from 'vuetify/lib/components/index.mjs'

const disabled = ref(true)

const dialog = ref(false)

onMounted(() => {
	setInterval(() => {
		disabled.value = !disabled.value
		console.log('disabled', disabled.value)
	}, 5000)
})
</script>

<template>
	<div>
		<VBtn @click="dialog = true">Open</VBtn>
		<VBtn>toto</VBtn>
		<VBtn>toto</VBtn>
		<DialogBox v-model="dialog">
			<button :disabled="disabled">random btn</button>
		</DialogBox>

		<VBtn>toto</VBtn>
		<VBtn>toto</VBtn>
		<VBtn>toto</VBtn>
		<VBtn>toto</VBtn>
	</div>
</template>

<style lang="scss" scoped></style>

```

</details>

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2024-08-20 13:38 UTC, VachetVirginie requested changes
Les tests ne passent pas

2024-08-29 07:49 UTC, VachetVirginie commented
Il manque un petit coup de linter ;)

2024-09-04 08:14 UTC, VachetVirginie approved these changes

2024-09-05 11:59 UTC, DavidFyon approved these changes

2024-09-05 12:02 UTC, DavidFyon commented on packages/synapse-bridge/src/elements/DialogBox/DialogBox.vue
> +				;(await this.getSelectableElements())[0].focus()
enlever le ; ?

2024-09-05 13:12 UTC, merged