✨ vue-dash: Add Cypress prompt
assurance-maladie-digital/design-system pull request #567
Opened 2020-09-18 15:05 UTC by mmi16389

# Description
Intégration de cypress via vue-dash

## Type de changement

- [x] Nouvelle fonctionnalité 
## Checklist

- [x] Ma Pull Request pointe vers la bonne branche
- [x] Mon code suit le style de code de ce projet
- [x] J'ai effectué une review de mon propre code
- [x] J'ai commenté mon code, en particulier dans les zones difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [x] Mes modifications ne génèrent aucun nouveau warning
- [x] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [x] J'ai mis à jour le fichier Changelog

2020-09-29 09:22 UTC, deraw reviewed
Je pense qu'il faudrait ajouter ceci dans le `.gitignore` :
```
# Cypress
/tests/e2e/videos/
/tests/e2e/screenshots/
```

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/prompts.js
> +		message: 'Utiliser cypress pour les tests e2e',
```suggestion
		message: 'Utiliser cypress pour les tests d\'interface',
```

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/support/index.ts
> +import './commands'
```suggestion
import './commands';

```

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/index.js
> +			cypress: true, // Disable cypress for now
Ici tu peux carrément supprimer la ligne il me semble
On avait mis `cypress: false` pour forcer la désactivation, en mettant `cypress: true` tu forces l'activation !
Il faudrait mettre `cypress: userOptions.cypress` mais c'est fait automatiquement quand on déstructure : `...userOptions`

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/plugins/index.js
> +	const options = {
Tu peux corriger l'indentation ici stp ?

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/tsconfig.json
> +}
```suggestion
}

```

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/tsconfig.json
> +  "compilerOptions": {
Est-ce que tu peux corriger l'indentation du fichier stp ?

2020-09-29 09:22 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/integration/home.spec.ts
> +		cy.get('.v-slide-group__wrapper>.v-slide-group__content>a').should('have.length', 2);
Je pense que ça serait plus propre d'utiliser des attributs `data-cy` dans le template et de cibler ceux-ci, car si la classe Vuetify change le test va planter alors que notre code n'a pas été modifié (https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements)

2020-09-29 09:30 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/index.js
> +			cypress: true, // Disable cypress for now
Je vois c'est noté :+1:

2020-09-29 09:31 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/integration/home.spec.ts
> +		cy.get('.v-slide-group__wrapper>.v-slide-group__content>a').should('have.length', 2);
C'est vrai, tu as tout à fait raison. J'ai pas pensé :+1:  Je vais faire la modif

2020-09-29 09:32 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/plugins/index.js
> +	const options = {
ça marche

2020-09-29 09:33 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/tsconfig.json
> +  "compilerOptions": {
ça marche

2020-09-30 15:25 UTC, deraw commented on .gitignore
> +/tests/e2e/screenshots/
```suggestion
/tests/e2e/screenshots/

```

2020-09-30 15:26 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/_eslintrc.js
> +	ignorePatterns: [ "tests/e2e/*"]
Pourquoi on ne voudrait pas passer la qual sur les tests ?

2020-10-02 14:51 UTC, BaptisteCool approved these changes

2020-10-02 14:51 UTC, BaptisteCool commented on packages/vue-cli-plugin-vue-dash/generator/template/_eslintrc.js
> +	ignorePatterns: [ "tests/e2e/*"]
Il me semble que j'ai eu ce souci de conflit avec jest. 🤔 
Mais a voir oui. Il est possible que l'on abandonne les tets unitaire (jest) sur les projets front au profit des tests fonctionnels selon Christophe.

2020-10-05 14:48 UTC, mmi16389 reviewed
oki

2020-10-05 16:21 UTC, deraw reviewed
Est-ce que tu peux repasser sur les fichiers et les indenter avec des tabulations stp ?

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
> +		newPackageProperties.devDependencies['@vue/cli-plugin-e2e-cypress'] = '^4.5.0';
```suggestion
		newPackageProperties.devDependencies['@vue/cli-plugin-e2e-cypress'] = '^4.5.6';
```

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/_eslintrc.js
> +	}
```suggestion
	}
```

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/_eslintrc.js
> +		'@typescript-eslint/triple-slash-reference': 'off'
Il faut laisser cette règle activée, les triple slash ne sont pas recommandés

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/_eslintrc.js
> +		'@typescript-eslint/no-unused-vars': 'off',
Qu'est-ce qui nécessite de désactiver cette règle ?

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/webpack.config.js
> +module.exports = {
Est-ce que tu peux utiliser des tabulations pour indenter le fichier stp ?

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/webpack.config.js
> +                            // skip type checking for speed
```suggestion
                            // Skip type checking for speed 
```

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/tsconfig.json
> +  "compilerOptions": {
Ce n'est toujours pas bon, il faut indenter avec des tabulations

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/support/index.ts
>  import './commands';
```suggestion

import './commands';
```

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/support/index.d.ts
> +}
```suggestion
}

```

2020-10-05 16:21 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/support/commands.ts
> +});
```suggestion
});

```

2020-10-05 19:11 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/_eslintrc.js
> +		'@typescript-eslint/triple-slash-reference': 'off'
Je vais faire la mise à jour, en la remplacant. Je me suis servi de l'exemple de l doc ce cypress... IL y a autre maniere de faire ;)

2020-10-05 19:12 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/_eslintrc.js
> +		'@typescript-eslint/no-unused-vars': 'off',
Honnetement, aucune; c'est un oubli.

2020-10-05 19:14 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/webpack.config.js
> +module.exports = {
Désolé, je vais voir ça. Il me semble mes configs me font des indents automatic après chaque commit. Je vais regler ça...

2020-10-07 15:26 UTC, mmi16389 reviewed
J'ai reverifié le contenu des fichiers....

2020-10-15 09:37 UTC, deraw requested changes
Il faudrait revoir le wording des tests (les blocs `it()`), il faut avoir la même qualité que dans les tests unitaires de Vue Dot

2020-10-15 09:37 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/HeaderMenu.vue
> +		data-cy="toolbar-elmt"
```suggestion
		data-cy="header-menu"
```

2020-10-15 09:37 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppToolbar.vue
> +			data-cy="tab-content-link"
```suggestion
			data-cy="toolbar-tabs"
```

2020-10-15 09:37 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/specs/doc_metadata.spec.ts
> +// https://docs.cypress.io/api/introduction/api.html
Comme discuté on peut supprimer ce test

2020-10-15 09:37 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/specs/toolbar.spec.ts
> +describe('Toolbar page', () => {
```suggestion
describe('Toolbar', () => {
```
Ce n'est pas une page !

2020-10-15 09:37 UTC, deraw commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/specs/toolbar.spec.ts
> +		cy.contains('div', 'Projet my-project-game');
Ici la valeur `my-project-game` ne peut pas être en dur, soit on utilise la variable du nom du projet soit on modifie le test

2020-10-15 09:38 UTC, deraw commented
Est-ce que c'est possible de mettre à jour le changelog aussi stp ? 🙂

2020-10-16 10:00 UTC, mmi16389 commented on packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/specs/doc_metadata.spec.ts
> +// https://docs.cypress.io/api/introduction/api.html
Tout à fait

2020-10-16 13:16 UTC, BaptisteCool approved these changes

2020-10-16 13:45 UTC, mmi16389 reviewed
oki

2020-11-10 15:23 UTC, deraw approved these changes

2020-11-10 15:33 UTC, Linaida approved these changes
Je vois une petite amélioration mais je sais pas si elle est faisable.
Ca serait de récupérer les uri directement depuis le router pour que les tests d'adapte automatiquement si elles changent

2020-11-10 15:36 UTC, merged