✨vue-dot: ajout bouton téléchargement
assurance-maladie-digital/design-system pull request #781
Opened 2020-12-08 14:24 UTC by BaptisteCool

## Description

Ajout du bouton de téléchargement avec une promise qui renvoi un fichier

Le composant prend en paramètre une promesse qui retourne le fichier (pour intégrer l'état de chargement et de succès)

## Type de changement

- Nouvelle fonctionnalité

## Checklist

- [x] Ma Pull Request pointe vers la bonne branche
- [ ] Mon code suit le style de code du projet
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai apporté les modifications correspondantes à la documentation
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications
- [ ] J'ai mis à jour le fichier Changelog

2020-12-11 16:02 UTC, BaptisteCool reviewed
Première PR même si tout n'est pas parfait comme il y a des choses nouvelles sur jest et les mock() que je ne maitrise pas encore.

2020-12-15 13:54 UTC, mmi16389 reviewed
Oki

2021-01-08 18:30 UTC, deraw requested changes

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/playground/examples/DownloadBtnEx.vue
> +
```suggestion
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/playground/examples/DownloadBtnEx.vue
> +
```suggestion
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/playground/examples/DownloadBtnEx.vue
> +					headers: { 'content-disposition': 'filebody' },
```suggestion
					headers: {
						'content-disposition': 'filebody'
					},
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue
> +					// Notify!
```suggestion
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue
> +					const message: string = typeof this.notification === 'boolean' ? locales.downloadSuccess : this.notification as string;
```suggestion
					const message = typeof this.notification === 'boolean' ? locales.downloadSuccess : this.notification as string;
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/elements/DownloadBtn/locales.ts
> +	downloadSuccess: 'Téléchargé avec succès'
```suggestion
	downloadSuccess: 'Document téléchargé avec succès'
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/elements/DownloadBtn/tests/DownloadBtn.spec.ts
> +const contentDispositionHeader = JSON.stringify({ type: 'inline', parameters: { filename: 'justificatif.pdf' } }) as string;
```suggestion
const contentDispositionHeader = JSON.stringify({
	type: 'inline',
	parameters: {
		filename: 'justificatif.pdf'
	}
});
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/elements/DownloadBtn/tests/DownloadBtn.spec.ts
> +	);
```suggestion
	resolve({
		data: 'test',
		status: 200,
		statusText: 'test status Text',
		headers: {
			'content-disposition': contentDispositionHeader
		},
		config: {}
	});
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/index.ts
> + * @param {BufferSource | Blob | string} content The content to download
C'est toujours le cas ? Il faut peut-être l'importer depuis `@types/node`

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +import { downloadFile } from '..';
```suggestion
import { downloadFile } from '../';
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +const file = new File(['hello world'], 'hello_world.txt', { type: 'text/plain' });
```suggestion
const file = new File(
	['hello world'],
	'hello_world.txt',
	{ type: 'text/plain' }
);
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +
```suggestion
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +
```suggestion
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/vue.config.js
> +const LIMIT_SIZE = 550000;
à enlever de la PR
Si tu en as besoin fait une première PR pour cette modif

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +	it('testing download IE10', () => {
On ne supporte pas IE10

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		} as any;
ça serait bien de typer cette variable

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +			style: jest.fn(()=>'none')
```suggestion
			style: jest.fn(() => 'none')
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +	it('is called correctly', () => {
Je pense qu'il faut reformuler les descriptions de tests
Par exemple ici tu peux mettre "it downloads a file correctly"
Et ainsi de suite pour les autres tests

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +			style : jest.fn(()=>'none')
```suggestion
			style : jest.fn(() => 'none')
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/index.ts
> +	 * \ufeff = encodage UTF-8.
```suggestion
	 * \ufeff = UTF-8 encoding
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```suggestion

		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		const appendChilSpy = jest.spyOn(document.body, 'appendChild').mockImplementation();
```suggestion
		const appendChildSpy = jest.spyOn(document.body, 'appendChild').mockImplementation();
```
Attention aux typos, je te conseille d'installer l'extension "Code Spell Check" pour ça

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		expect(appendChilSpy).toHaveBeenCalledTimes(1);
```suggestion
		expect(appendChildSpy).toHaveBeenCalledTimes(1);
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```suggestion

		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		downloadFile(file, file.name, file.type, true);
```suggestion

		downloadFile(file, file.name, file.type, true);

```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```suggestion

		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```

2021-01-08 18:30 UTC, deraw commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```suggestion

		jest.spyOn(document, 'createElement').mockImplementation(() => link);
```

2021-01-12 10:42 UTC, BaptisteCool commented on packages/vue-dot/src/functions/downloadFile/index.ts
> + * @param {BufferSource | Blob | string} content The content to download
C'est un type trouver dans 'typescript/lib/lib.dom.d.ts' mais qui n'est pas exporter
type BufferSource = ArrayBufferView | ArrayBuffer;

Je créé un fichier 'types.d.ts' avec ce type dedans.

![image](https://user-images.githubusercontent.com/6760432/104303630-9b443e80-54ca-11eb-8f6b-aab92df982bd.png)

2021-01-12 10:49 UTC, BaptisteCool commented on packages/vue-dot/src/functions/downloadFile/tests/downloadFile.spec.ts
> +	it('testing download IE10', () => {
Effectivement, je met `test download from navigator version that contain \'.NET\'`

a la place

2021-02-06 19:10 UTC, deraw approved these changes

2021-02-06 19:28 UTC, merged